### ISSUE TITLE
Kernel module loading is broken on 3.8.0-25?

### ISSUE THREAD

**Issue by ku1ik** [fgrehm/vagrant-lxc#104]
I upgraded my kernel on Ubuntu 13.04 recently (just by apt-get upgrade) and restarted.
Since then when I try to enable firewall on a raring VM with `ufw enable` I get following:

```
[Errno 2] libkmod: ERROR ../libkmod/libkmod.c:554 kmod_search_moddep: could not open moddep file '/lib/modules/3.8.0-25-generic/modules.dep.bin'
ip6tables v1.4.12: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
```

I checked /lib/modules/ directory and it's not there but that's the same raring image that worked before so the issue must be hidden somewhere else. 

Full output (from vagrant up to the above error) here:
https://gist.github.com/sickill/5935636

**Comment by iamjvn** [comment]
It seems this change has broken the synced_folder "/lib/modules" workaround.

```
lxc-start 20170622002807.856 ERROR    lxc_utils - utils.c:open_without_symlink:1682 - Too many levels of symbolic links - lib in /usr/lib/x86_64-linux-gnu/lxc/lib/modules was a symbolic link!
lxc-start 20170622002807.857 ERROR    lxc_conf - conf.c:mount_entry:1708 - Too many levels of symbolic links - failed to mount '/lib/modules' on '/usr/lib/x86_64-linux-gnu/lxc/lib/modules'
```
