### ISSUE TITLE
lxc-create fails on Arch Linux

### ISSUE THREAD

**Issue by bryanalves** [fgrehm/vagrant-lxc#109]
I added the quantal64 box, and create a base Vagrantfile with vagrant init.  When running vagrant up however, I get a failure with the following log:

---

 INFO global: Vagrant version: 1.2.2
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/kernel_v2/plugin.rb
 INFO manager: Registered plugin: kernel
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/hosts/windows/plugin.rb
 INFO manager: Registered plugin: Windows host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/hosts/linux/plugin.rb
 INFO manager: Registered plugin: Linux host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/hosts/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/hosts/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/hosts/opensuse/plugin.rb
 INFO manager: Registered plugin: OpenSUSE host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/hosts/fedora/plugin.rb
 INFO manager: Registered plugin: Fedora host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/hosts/arch/plugin.rb
 INFO manager: Registered plugin: Arch host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/hosts/bsd/plugin.rb
 INFO manager: Registered plugin: BSD host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/provisioners/shell/plugin.rb
 INFO manager: Registered plugin: shell
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/provisioners/ansible/plugin.rb
 INFO manager: Registered plugin: ansible
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/provisioners/chef/plugin.rb
 INFO manager: Registered plugin: chef
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/provisioners/puppet/plugin.rb
 INFO manager: Registered plugin: puppet
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/provisioners/cfengine/plugin.rb
 INFO manager: Registered plugin: CFEngine Provisioner
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/status/plugin.rb
 INFO manager: Registered plugin: status command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/suspend/plugin.rb
 INFO manager: Registered plugin: suspend command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/destroy/plugin.rb
 INFO manager: Registered plugin: destroy command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/halt/plugin.rb
 INFO manager: Registered plugin: halt command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/init/plugin.rb
 INFO manager: Registered plugin: init command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/plugin/plugin.rb
 INFO manager: Registered plugin: plugin command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/provision/plugin.rb
 INFO manager: Registered plugin: provision command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/up/plugin.rb
 INFO manager: Registered plugin: up command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/ssh_config/plugin.rb
 INFO manager: Registered plugin: ssh-config command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/package/plugin.rb
 INFO manager: Registered plugin: package command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/reload/plugin.rb
 INFO manager: Registered plugin: reload command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/ssh/plugin.rb
 INFO manager: Registered plugin: ssh command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/box/plugin.rb
 INFO manager: Registered plugin: box command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/resume/plugin.rb
 INFO manager: Registered plugin: resume command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/communicators/ssh/plugin.rb
 INFO manager: Registered plugin: ssh communicator
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/guests/ubuntu/plugin.rb
 INFO manager: Registered plugin: Ubuntu guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/guests/openbsd/plugin.rb
 INFO manager: Registered plugin: OpenBSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/guests/linux/plugin.rb
 INFO manager: Registered plugin: Linux guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/guests/debian/plugin.rb
 INFO manager: Registered plugin: Debian guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/guests/solaris/plugin.rb
 INFO manager: Registered plugin: Solaris guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/guests/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/guests/suse/plugin.rb
 INFO manager: Registered plugin: SUSE guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/guests/redhat/plugin.rb
 INFO manager: Registered plugin: RedHat guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/guests/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/guests/fedora/plugin.rb
 INFO manager: Registered plugin: Fedora guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/guests/arch/plugin.rb
 INFO manager: Registered plugin: Arch guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/guests/pld/plugin.rb
 INFO manager: Registered plugin: PLD Linux guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/kernel_v1/plugin.rb
 INFO manager: Registered plugin: kernel
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/providers/virtualbox/plugin.rb
 INFO manager: Registered plugin: VirtualBox provider
 INFO vagrant: `vagrant` invoked: ["up", "--provider=lxc"]
DEBUG vagrant: Creating Vagrant environment
 INFO environment: Environment initialized (#Vagrant::Environment:0x000000023a1b30)
 INFO environment:   - cwd: /home/balves/src/blah
 INFO environment: Home path: /home/balves/.vagrant.d
 INFO environment: Local data path: /home/balves/src/blah/.vagrant
DEBUG environment: Creating: /home/balves/src/blah/.vagrant
DEBUG environment: Loading plugins from: /home/balves/.vagrant.d/plugins.json
 INFO environment: Loading plugin from JSON: vagrant-lxc
 INFO manager: Registered plugin: Linux Containers (LXC) provider
 INFO environment: Running hook: environment_load
 INFO environment: Initializing config...
 INFO loader: Set :default = "/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/config/default.rb"
DEBUG loader: Populating proc cache for "/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/config/default.rb"
DEBUG loader: Load procs for pathname: /opt/vagrant/embedded/gems/gems/vagrant-1.2.2/config/default.rb
 INFO loader: Set :root = #Pathname:/home/balves/src/blah/Vagrantfile
DEBUG loader: Populating proc cache for #Pathname:/home/balves/src/blah/Vagrantfile
DEBUG loader: Load procs for pathname: /home/balves/src/blah/Vagrantfile
 INFO loader: Loading configuration in order: [:default, :home, :root]
DEBUG loader: Loading from: default (evaluating)
DEBUG loader: Loading from: root (evaluating)
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG hosts: Host path search classes: [VagrantPlugins::HostWindows::Host, VagrantPlugins::HostArch::Host, VagrantPlugins::HostFedora::Host, VagrantPlugins::HostGentoo::Host, VagrantPlugins::HostFreeBSD::Host, VagrantPlugins::HostOpenSUSE::Host, VagrantPlugins::HostLinux::Host, VagrantPlugins::HostBSD::Host]
 INFO hosts: Host class: VagrantPlugins::HostArch::Host
 INFO runner: Running action: #Vagrant::Action::Builder:0x0000000261c928
 INFO cli: CLI: [] "up" ["--provider=lxc"]
DEBUG cli: Invoking command class: VagrantPlugins::CommandUp::Command ["--provider=lxc"]
DEBUG command: 'Up' each target VM...
DEBUG command: Getting target VMs for command. Arguments:
DEBUG command:  -- names: []
DEBUG command:  -- options: {:provider=>"lxc"}
DEBUG command: Loading all machines...
 INFO environment: Getting machine: default (lxc)
 INFO environment: Uncached load of machine.
 INFO loader: Set :vm_default = []
 INFO loader: Loading configuration in order: [:default, :home, :root, :vm_default]
DEBUG loader: Loading from: default (cache)
DEBUG loader: Loading from: root (cache)
DEBUG loader: Configuration loaded successfully, finalizing and returning
 INFO environment: Provider-supported box formats: [:lxc]
 INFO box_collection: Searching for box: quantal64-lxc (lxc) in /home/balves/.vagrant.d/boxes/quantal64-lxc/lxc/metadata.json
 INFO box_collection: Box found: quantal64-lxc (lxc)
 INFO environment: Box found with format: lxc
 INFO machine: Initializing machine: default
 INFO machine:   - Provider: Vagrant::LXC::Provider
 INFO machine:   - Box: #Vagrant::Box:0x000000029541b8
 INFO machine:   - Data dir: /home/balves/src/blah/.vagrant/machines/default/lxc
DEBUG lxc: Instantiating the container for: nil
 INFO subprocess: Starting process: ["sudo", "lxc-version"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: lxc version: 0.9.0
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31998
DEBUG subprocess: Exit status: 0
 INFO command: With machine: default (LXC (new VM))
 INFO interface: info: Bringing machine 'default' up with 'lxc' provider...
 INFO batch_action: Enabling parallelization by default.
 INFO batch_action: Disabling parallelization because provider doesn't support it: lxc
 INFO batch_action: Batch action will parallelize: false
 INFO batch_action: Starting action: #Vagrant::Machine:0x00000002e01a30 up {:parallel=>true, :provision_enabled=>true, :provision_types=>nil, :provider=>"lxc"}
 INFO machine: Calling action: up on provider LXC (new VM)
 INFO runner: Running action: #Vagrant::Action::Builder:0x000000029d4070
 INFO warden: Calling action: #Vagrant::Action::Builtin::ConfigValidate:0x00000002fa1c78
 INFO warden: Calling action: #Vagrant::Action::Builtin::Call:0x00000002fa1c50
 INFO runner: Running action: #Vagrant::Action::Builder:0x000000029a19b8
 INFO warden: Calling action: #Vagrant::LXC::Action::Created:0x000000029a78b8
 INFO runner: Running action: #Vagrant::Action::Warden:0x00000002eda5b0
 INFO warden: Calling action: #Vagrant::Action::Builtin::HandleBoxUrl:0x00000002eda538
 INFO warden: Calling action: #Vagrant::LXC::Action::HandleBoxMetadata:0x00000002eda510
 INFO interface: info: Importing base box 'quantal64-lxc'...
DEBUG handle_box_metadata: Validating box contents
DEBUG handle_box_metadata: Setting box options on environment
 INFO warden: Calling action: #Vagrant::LXC::Action::Create:0x00000002cc3588
DEBUG driver: Copying LXC template into place
DEBUG driver: Creating container...
 INFO subprocess: Starting process: ["sudo", "lxc-create", "--template", "vagrant-tmp-blah-1373249959", "--name", "blah-1373249959", "--", "--arch", "amd64", "--release", "quantal", "--tarball", "/home/balves/.vagrant.d/boxes/quantal64-lxc/lxc/rootfs.tar.gz", "--auth-key", "/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/keys/vagrant.pub"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: 
DEBUG subprocess: stdout: lxc-create: No config file specified, using the default config /etc/lxc/default.conf
DEBUG subprocess: stdout: Extracting /home/balves/.vagrant.d/boxes/quantal64-lxc/lxc/rootfs.tar.gz ...
DEBUG subprocess: stderr: chroot: failed to run command ‘useradd’: No such file or directory
DEBUG subprocess: stderr: lxc-create: failed to execute template 'vagrant-tmp-blah-1373249959'
DEBUG subprocess: stderr: lxc-create: aborted
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31997
DEBUG subprocess: Exit status: 1
ERROR warden: Error occurred: There was an error executing ["sudo", "lxc-create", "--template", "vagrant-tmp-blah-1373249959", "--name", "blah-1373249959", "--", "--arch", "amd64", "--release", "quantal", "--tarball", "/home/balves/.vagrant.d/boxes/quantal64-lxc/lxc/rootfs.tar.gz", "--auth-key", "/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/keys/vagrant.pub"]

For more information on the failure, enable detailed logging by setting
the environment variable VAGRANT_LOG to DEBUG.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: There was an error executing ["sudo", "lxc-create", "--template", "vagrant-tmp-blah-1373249959", "--name", "blah-1373249959", "--", "--arch", "amd64", "--release", "quantal", "--tarball", "/home/balves/.vagrant.d/boxes/quantal64-lxc/lxc/rootfs.tar.gz", "--auth-key", "/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/keys/vagrant.pub"]

For more information on the failure, enable detailed logging by setting
the environment variable VAGRANT_LOG to DEBUG.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #Vagrant::Action::Builtin::Call:0x00000002fa1c50
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Running hook: environment_unload
 INFO runner: Running action: #Vagrant::Action::Builder:0x00000002da2c38
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::LXC::Errors::ExecuteError: There was an error executing ["sudo", "lxc-create", "--template", "vagrant-tmp-blah-1373249959", "--name", "blah-1373249959", "--", "--arch", "amd64", "--release", "quantal", "--tarball", "/home/balves/.vagrant.d/boxes/quantal64-lxc/lxc/rootfs.tar.gz", "--auth-key", "/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/keys/vagrant.pub"]

For more information on the failure, enable detailed logging by setting
the environment variable VAGRANT_LOG to DEBUG.>
ERROR vagrant: There was an error executing ["sudo", "lxc-create", "--template", "vagrant-tmp-blah-1373249959", "--name", "blah-1373249959", "--", "--arch", "amd64", "--release", "quantal", "--tarball", "/home/balves/.vagrant.d/boxes/quantal64-lxc/lxc/rootfs.tar.gz", "--auth-key", "/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/keys/vagrant.pub"]

For more information on the failure, enable detailed logging by setting
the environment variable VAGRANT_LOG to DEBUG.
ERROR vagrant: /home/balves/.vagrant.d/gems/gems/vagrant-lxc-0.3.4/lib/vagrant-lxc/driver/cli.rb:136:in `block in execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/util/retryable.rb:17:in`retryable'
/home/balves/.vagrant.d/gems/gems/vagrant-lxc-0.3.4/lib/vagrant-lxc/driver/cli.rb:126:in `execute'
/home/balves/.vagrant.d/gems/gems/vagrant-lxc-0.3.4/lib/vagrant-lxc/driver/cli.rb:108:in`run'
/home/balves/.vagrant.d/gems/gems/vagrant-lxc-0.3.4/lib/vagrant-lxc/driver/cli.rb:56:in `create'
/home/balves/.vagrant.d/gems/gems/vagrant-lxc-0.3.4/lib/vagrant-lxc/driver.rb:41:in`block in create'
/home/balves/.vagrant.d/gems/gems/vagrant-lxc-0.3.4/lib/vagrant-lxc/driver.rb:126:in `import_template'
/home/balves/.vagrant.d/gems/gems/vagrant-lxc-0.3.4/lib/vagrant-lxc/driver.rb:39:in`create'
/home/balves/.vagrant.d/gems/gems/vagrant-lxc-0.3.4/lib/vagrant-lxc/action/create.rb:14:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in`call'
/home/balves/.vagrant.d/gems/gems/vagrant-lxc-0.3.4/lib/vagrant-lxc/action/handle_box_metadata.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/handle_box_url.rb:72:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/util/busy.rb:19:in`busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/call.rb:51:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/config_validate.rb:25:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builder.rb:116:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/util/busy.rb:19:in`busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/machine.rb:147:in`action'
/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/batch_action.rb:63:in `block (2 levels) in run'
 INFO interface: error: There was an error executing ["sudo", "lxc-create", "--template", "vagrant-tmp-blah-1373249959", "--name", "blah-1373249959", "--", "--arch", "amd64", "--release", "quantal", "--tarball", "/home/balves/.vagrant.d/boxes/quantal64-lxc/lxc/rootfs.tar.gz", "--auth-key", "/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/keys/vagrant.pub"]

For more information on the failure, enable detailed logging by setting
the environment variable VAGRANT_LOG to DEBUG.
There was an error executing ["sudo", "lxc-create", "--template", "vagrant-tmp-blah-1373249959", "--name", "blah-1373249959", "--", "--arch", "amd64", "--release", "quantal", "--tarball", "/home/balves/.vagrant.d/boxes/quantal64-lxc/lxc/rootfs.tar.gz", "--auth-key", "/opt/vagrant/embedded/gems/gems/vagrant-1.2.2/keys/vagrant.pub"]

For more information on the failure, enable detailed logging by setting
the environment variable VAGRANT_LOG to DEBUG.

---

Am I missing a package?

**Comment by malaniz** [comment]
I'm having the same problem @iv597 Do you fix it?
