### ISSUE TITLE
Document setup for Arch Linux hosts

### ISSUE THREAD

**Issue by fgrehm** [fgrehm/vagrant-lxc#123]
See @riccieri's comment on https://github.com/fgrehm/vagrant-lxc/issues/109#issuecomment-21274392, it is also being referenced on ArchLinux wiki: https://wiki.archlinux.org/index.php/Vagrant#vagrant-lxc

**Comment by fgrehm** [comment]
Apparently what we got on https://github.com/fgrehm/vagrant-lxc/wiki/Usage-on-Arch-Linux-hosts is enough!

**Comment by Jbonnett** [comment]
added: 
```
echo "net.ipv4.ip_forward=1"> /etc/sysctl.d/ip_forward.conf
sysctl net.ipv4.ip_forward=1
```

which should fix the network on reboot. 


though you may not have wanted me to edit the wiki directly.

**Comment by aanjaneyam** [comment]
> Apparently what we got on https://github.com/fgrehm/vagrant-lxc/wiki/Usage-on-Arch-Linux-hosts is enough!

What are the options for people using network manager in arch based distros like Manjaro.
