### ISSUE TITLE
Document setup for CentOS hosts

### ISSUE THREAD

**Issue by fgrehm** [fgrehm/vagrant-lxc#125]
I have no idea how this look like

**Comment by bear0330** [comment]
I have done this on CentOS 7, I am not sure it works perfectly but I can install iRedmail inside it and forward ports, it works fine until now.
1. Follow Fedora's install instruction: https://github.com/fgrehm/vagrant-lxc/wiki/Usage-on-fedora-hosts
There is something different, you must also install lxc-templates: `sudo yum install lxc lxc-libs lxc-templates`.

2. redir is not available on CentOS 7, you must compile it by yourself: 
    wget http://sammy.net/~sammy/hacks/redir-2.2.1.tar.gz
    tar xvfz redir-2.2.1.tar.gz
    cd redir-2.2.1
    make
    cp redir /usr/local/sbin

3. Install vagrant-lxc requires gcc-c++: `sudo yum install gcc-c++; vagrant plugin install vagrant-lxc`

4. Use the existing virbr0 provided by libvirtd, we must use johnwchadwick's approach in #308: 
    sudo yum install libvirt bridge-utils
    sudo systemctl enable libvirtd.service libvirt-guests.service
    sudo systemctl start libvirtd.service libvirt-guests.service
    sudo virsh net-autostart default

5. /etc/lxc/default.conf:
    lxc.network.type = veth
    lxc.network.link = virbr0
    lxc.network.flags = up
    lxc.network.ipv4 = 0.0.0.0/24

Now, it should work.

**Comment by fgrehm** [comment]
Awesome! I'll give it a try on a VM as soon as I have a chance. Thanks for reaching out!

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
