### ISSUE TITLE
conf needs lxc.autodev=true on host with systemd

### ISSUE THREAD

**Issue by cwoac** [fgrehm/vagrant-lxc#145]
I'm not sure what this will do on boxes which don't use systemd, but if you _don't_ have this then you get pts allocation errors on ones which do (arch, suse and I think the next fedora?)

I'd submit a pull, but would need prodding of the effect on other hosts.

**Comment by malaniz** [comment]
@fgrehm i'm having this issue too. Just after an arch update. Do you know what would be a path to find a solution?

**Comment by fgrehm** [comment]
Sorry I don't use this plugin anymore, please open a new issue so that it is easier for others to find and reach out 🍻
