### ISSUE TITLE
Investigate lxc 1.0 / Ubuntu 13.10 issues

### ISSUE THREAD

**Issue by fgrehm** [fgrehm/vagrant-lxc#150]
Fork of @gwillem's comment on https://github.com/fgrehm/vagrant-lxc/issues/129#issuecomment-24694052

> Same issue with lxc 1.0.0~alpha1-0ubuntu3 from Ubuntu 13.10 beta. @fgrehm's template yields another error:
> 
> ``` bash
>  INFO subprocess: Starting process: ["/usr/bin/sudo", "/home/willem/bin/lxc-vagrant-wrapper", "lxc-start", "-d", "--name", "precise01-1379533350"]
> DEBUG subprocess: Selecting on IO
> DEBUG subprocess: stderr: lxc-start: command get_init_pid failed to receive response
> DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31994
> DEBUG subprocess: Exit status: 255
> ERROR warden: Error occurred: There was an error executing ["sudo", "/home/willem/bin/lxc-vagrant-wrapper", "lxc-start", "-d", "--name", "precise01-1379533350"]
> ```
> 
> I then added the [ubuntu-lxc ppa](https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/1227092/comments/2) and installed version 1.0.0~alpha1+staging~20130916-1417-0ubuntu1~ppa1~saucy1 but now the error is changed into:
> 
> ```
> lxc-start: command get_cgroup failed to receive response
> ```

@rrerolle [also reported](https://github.com/fgrehm/vagrant-lxc/issues/129#issuecomment-24808595) that he was having issues and @MSch has [mentioned](https://github.com/fgrehm/vagrant-lxc/issues/129#issuecomment-24811082) that "With lxc 1.0 `lxc-shutdown` has been renamed to `lxc-stop`"

**Comment by vdloo** [comment]
thanks @gwillem I googled this error!
