### ISSUE TITLE
Shared folders permission problem

### ISSUE THREAD

**Issue by fgrehm** [fgrehm/vagrant-lxc#151]
While trying out [this](http://goo.gl/Y4aRr) Ubuntu Raring Vagrant VBox VM, I stumbled across a pretty bad issue that messes up with shared folders permissions. The problem is that the `vagrant` user on that VBox VM has an `uid` of `900`, but the base boxes containers ship with the `vagrant` user with the `uid` of `1000`.

The reason why things works fine for most cases is that Debian-like distros uses 1000 as the initial user id which usually maps to the same user id on the host machine.

Unfortunately I have no idea how to mount the shared folder on the guest container with a different `uid` / `gid`, a solution might be to implement support for NFS Shared folders to work around that for those who face this problem but I'd need to double check that. If you are experiencing this, please raise your hand :)

**Comment by twolfson** [comment]
I'm not sure about other users but I am considering using `vagrant-lxc` because NFS and rsync are too slow for my needs. As a result, suggesting those as a workaround is backwards =/

As an alternative, I wrote a script to update the `vagrant` user's UID and GID to match the host machine's UID/GID. I wasn't able to use `usermod` (which would have made things much simpler) due to the host OS complaining about `vagrant` user being in use (even though it wasn't). Here's the script I am using in my Vagrantfile:

```ruby
# Repair Vagrant UID/GID to match our current user
uid = `id -u`.strip()
gid = `id -g`.strip()
config.vm.provision "shell", inline: <<-EOF
  # Exit on first error
  set -e

  # Resolve our UID and GID
  src_uid="$(id -u vagrant)"
  target_uid="#{uid}"
  src_gid="$(id -g vagrant)"
  target_gid="#{gid}"

  # If the user and group ids are aligned, then exit early
  if test "$src_uid" = "$target_uid" && test "$src_gid" = "$target_gid"; then
    exit 0
  fi

  # Otherwise, update our user id and group id
  # DEV: We cannot use \`usermod\` as it complains about \`vagrant\` having a process
  # Example: UID=100; GID=101
  #  /etc/shadow: libuuid:x:100:101::/var/lib/libuuid:
  #  /etc/group: libuuid:x:101:
  sed -E "s/(vagrant:.:)$src_uid:$src_gid:/\\1$target_uid:$target_gid:/g" --in-place /etc/passwd
  sed -E "s/(vagrant:.:)$src_gid:/\\1$target_gid:/g" --in-place /etc/group

  # Update all files to the proper user and group
  find / -uid "$src_uid" 2> /dev/null | grep --invert-match -E "^(/sys|/proc)" | xargs chown "$target_uid"
  find / -gid "$src_gid" 2> /dev/null | grep --invert-match -E "^(/sys|/proc)" | xargs chgrp "$target_gid"
EOF
```

**Comment by fgrehm** [comment]
@twolfson I know it's been a while but you can also create a base box with the proper GID / UID 😄

**Comment by twolfson** [comment]
@fgrehm I think that would work for a single user but what if your team has multiple machines with different GID/UID =/

**Comment by fgrehm** [comment]
oh yeah, that sucks. its been a while since I last done any LXC work but last time I looked into this NFS was the only way I could get it working

**Comment by twolfson** [comment]
After some searching, it looks like there's a `id_map` config that should work:

https://github.com/lxc/lxc/issues/1176

https://linuxcontainers.org/lxc/manpages/man5/lxc.container.conf.5.html#lbBB

```ruby
  config.vm.provider "lxc" do |lxc|
    config.vm.box = "fgrehm/trusty64-lxc"
    lxc.customize("id_map", "u 1000 1001 1")
    lxc.customize("id_map", "g 1000 1001 1")
    # Later on, use #{uid} with uid = `id -u`.strip() from previous iteration
  end
```

I tried to get it working but couldn't. Unfortunately, I'm out of time to explore it but thankfully the script I posted has been working well for me =)

**Comment by bryanlarsen** [comment]
@twolfson, your script appears to be working great for me.   I had to add a '-print0' to the find script and use '-0' to xargs because we have some filenames with spaces.  Thanks!

**Comment by twolfson** [comment]
Ah, null delimiter. Nice catch, I'll update the comment :+1:
