### ISSUE TITLE
Losing network connectivity when container with lowest mac address shuts down

### ISSUE THREAD

**Issue by oker1** [fgrehm/vagrant-lxc#240]
This is not really an issue with vagrant-lxc, I just thought i would share it here to help others. We are running jenkins builds starting vagrant boxes, then running tests with vagrant ssh -c "...". Sometimes these builds got stuck in jenkins randomly, never finishing. I've traced this back to the behavior of bridges. If a bridge has no mac address set, it'll have the lowest of it's connected intefaces mac addresses. If the lowest mac address gets removed from the bridge, the mac address changes. This causes a short loss of connectivity on the other interfaces in the bridge. This can be avoided if you set a low enough mac address on the bridge, like `ip link set lxcbr0 address 00:16:30:4a:31:7c`. More information: https://lists.linuxcontainers.org/pipermail/lxc-users/2011-October/002816.html

Maybe the plugin could warn you if you don't have a proper mac address set on the bridge used.

**Comment by ccope** [comment]
Heh, we've hit this in a very similar scenario as oker1. According to other sources, you can't set an arbitrary MAC address on a bridge, it has to be that of another interface on the bridge. The workaround I've seen posted is to add a dummy interface on the bridge with a MAC address that is lower than the range for containers. I'm going to see if this can be fixed upstream.

```
modprobe dummy
ip link add name dummy0 address "f0:00:00:00:00:00" type dummy
ip link set dev dummy0 master lxcbr0
```

**Comment by ccope** [comment]
https://github.com/lxc/lxc/issues/604
