### ISSUE TITLE
Using sudo_user freezes indefinitely 

### ISSUE THREAD

**Issue by aboudreault** [fgrehm/vagrant-lxc#285]
I'm experiencing an issue with vagrant provision with an ansible playbook

The following task is freeze when using lxc as provider:

```
- name: say hi
  tags: foo
  shell: echo "hi..."
  sudo_user: "{{ edx_ansible_user }}"
```

1. The playbook works well using virtualbox provider.
2. The issue is ONLY happening when using sudo_user: "{{ edx_ansible_user }}"
3. The issue is NOT happening if I use root, sudo_user: "root"
4. The vagrant user doesn't require password, --> %sudo ALL=NOPASSWD:ALL
5. This is how ansible create the user:

```
- name: create application user
  user: >
    name="{{ edx_ansible_user }}"
    home="{{ edx_ansible_app_dir }}"
    createhome=no
    shell=/bin/false
```

Let me know if I can provider anything else.

**Comment by aboudreault** [comment]
hey @fgrehm! I've just retested everything with latest versions of all software and I can't reproduce the sudo freeze anymore. Closing.

**Comment by fgrehm** [comment]
Great!
