### ISSUE TITLE
How to use a different LXCPATH?

### ISSUE THREAD

**Issue by madhatter** [fgrehm/vagrant-lxc#293]
Because I don't have too much space available in /var/lib, I changed the LXCPATH in /etc/lxc/lxc.conf to "/export/storage/lxc" and changed the ROOTFS path in the base-box scripts to create new box images.
But when I now try to use one of these boxes with "vagrant up --provider=lxc" it fails almost immediately when trying to call "sudo cat /var/lib/lxc/vagrant-lxc_default_1401559462299_57499/config". It seems that the lxc provider does not know about the changed lxcpath.

**Comment by bryanlarsen** [comment]
I presume this was fixed in https://github.com/fgrehm/vagrant-lxc/pull/317

**Comment by gregoryolsen** [comment]
A bind mount will work as a *band-aid* solution.

I believe pull request #413 actually fixes this correctly, however it 
has yet to be merged.

Disclosure: I'm the author of #413.
