### ISSUE TITLE
14.04 box selinux problem

### ISSUE THREAD

**Issue by jalberto** [fgrehm/vagrant-lxc#301]
When using vagrant-lxc 1.0 + 14.04 premade box I need to run this manually so apt-get & dpkg works properly :

mount -o remount,ro,bind /sys/fs/selinux

This solves problems with selinux in Fedora host

**Comment by agriffis** [comment]
The existing behavior has two undesirable effects:
1. dpkg failures, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=734193
2. messes up host filesystem labels, so that ssh into the host does this:
```
$ ssh metis
Unable to get valid context for aron
```

I'll make a PR.

**Comment by fgrehm** [comment]
This should be fixed with https://github.com/fgrehm/vagrant-lxc/pull/357!
