### ISSUE TITLE
sudo wrapper doesn't allow backing store options

### ISSUE THREAD

**Issue by imobach** [fgrehm/vagrant-lxc#310]
Hi all,

I've been using vagrant-lxc for a while (thank you for such a great plugin!) and I'm having troubles when trying to use LVM as backend. As far as I know, sudo wrapper (/usr/local/bin/vagrant-lxc-wrapper-1.0.0.alpha.3) checks the arguments passed to the LXC commands.

The whitelist for `lxc-create` is:

<pre>
'/usr/bin/lxc-create', '-B', /.*/, '--template', /.*/, '--name', /.*/, '**'
</pre>

When using `lvm` as backend, some additional options (as volume group name, size, etc.) will sit just between `-B` an `--template` options. I mean:
<pre>
lxc-create -B lvm --lvname myvol --vgname mygroup --fssize 3G --fstype ext4 --template vagrant --name rails_default_1407965073263_99679
</pre>

So I guess that when the whitelist is applied, it fails on `--lvname` (or `--vgname`, etc.).

Or maybe am I doing something wrong?

For the records, I'm using OpenSUSE Factory.

Thank you in advance!

**Comment by fgrehm** [comment]
This should have been fixed by the commit above. Sorry it took so long!

**Comment by imobach** [comment]
Thank you Fabio. It seems to be working now.

**Comment by jefmathiot** [comment]
@fgrehm I missed the notification of your ping, sorry to both of you @imobach. I'd have been glad to help :(
