### ISSUE TITLE
Use unprivileged container

### ISSUE THREAD

**Issue by ogai** [fgrehm/vagrant-lxc#312]
_vagrant-lxc_ should create an [unprivileged container](https://www.stgraber.org/2014/01/17/lxc-1-0-unprivileged-containers/) (lxc container in userspace) for security reasons: _vagrant_ and e.g. _virtualbox_ also run in userspace. The necessity to give _vagrant-lxc_ root rights (sudo) is a show-stopper.

Granted, _vagrant_ and _virtualbox_ must be installed with root privileges too, but they are signed packages tested and distributed by main Linux distributions like Ubuntu and Debian.

**Comment by ccope** [comment]
This seems pretty straightforward to do (works for me on Ubuntu 14.04, kernel 3.13, lxc 1.1.0 from the official PPA): https://help.ubuntu.com/lts/serverguide/lxc.html#lxc-unpriv
Looks like the following needs to be implemented in vagrant-lxc:
 - [ ] an option to designate machines and boxes as 'privileged' or 'unprivileged'
 - [ ] check that the necessary config files are in place
    - [ ] and initialize them if not
 - [ ] add a function to wrap commands with sudo depending whether the machine is privileged or not
 - [ ] switchable root directory for storing containers
 - [ ] prebuilt unprivileged boxes on vagrantcloud

**Comment by fgrehm** [comment]
@ccope I like that plan, if you want to kick that off I can give you commit access to this repo so we can collaborate on a branch :smile:  WDYT?

**Comment by ccope** [comment]
Sure, sounds good.

**Comment by fgrehm** [comment]
@ccope Welcome aboard!

Feel free to push some code to the `unprivileged-containers` branch :beers:

**Comment by jseadragon** [comment]
Any progress on this? It'd be super sweet to have this :D

**Comment by fgrehm** [comment]
Not that I'm aware of :eyes:

**Comment by jseadragon** [comment]
Would this be something I could help out with?

**Comment by hsoft** [comment]
I began working on it. See conversation in #447. It *seems* straightforward to achieve, but in fact there's many moving parts (sudo wrapper, brctl, container paths...) + the necessity of not breaking the current workflow. I'm planning on slowly "de-hardcode" stuff for an upcoming 1.3 release and then add a new `privileged` flag for a v1.4 release.

**Comment by hsoft** [comment]
I've just pushed support for unprivileged containers to `master`. Anyone here wants to try it out and let me know how it works for them?

(re-opening the ticket, I think I was a bit too quick to close the ticket)

**Comment by fgrehm** [comment]
@hsoft this is HUGE man! Thanks a lot for working on it 😄 even though I'm no longer using the plugin these days I might be able to help testing this out... would u be able to put up a vbox VM like https://github.com/fgrehm/vagrant-lxc-vbox-hosts for me to test things out?

**Comment by hsoft** [comment]
@fgrehm sorry I'm not set up with virtualbox on my dev machines. I'm on `no-multilib` on gentoo and vbox requires x86. It would be quite time consuming for me to make that kind of setup for you.

**Comment by hsoft** [comment]
Oh well, let's just release the thing and see how it goes. After all, it's just a non-default new option.
