### ISSUE TITLE
sudo wrapper use "embedded" ruby unconditionally

### ISSUE THREAD

**Issue by avnik** [fgrehm/vagrant-lxc#319]
When I run `vagrant lxc sudoers` -- I have got script in /usr/local/bin with wollowing shebang:

```
#!/opt/vagrant/embedded/bin/ruby
```

(even if I used vagrant installed via debian repo, or install using bundler and gemfile -- which both obiviously use system provided ruby from /usr/bin/ruby)

**Comment by MyChaOS87** [comment]
I can confirm this is not working on debian (testing/stretch)
would it be possible to just check if `/opt/vagrant/embedded/bin/ruby` even exists, which is not the case in my environment

Workaround:
```
sudo mkdir -p /opt/vagrant/embedded/bin/
sudo ln -s `which ruby` /opt/vagrant/embedded/bin/ruby
```
