### ISSUE TITLE
"VirtualBox like" snapshot

### ISSUE THREAD

**Issue by fgrehm** [fgrehm/vagrant-lxc#32]
Could possibly be handled by `lxc-clone`. See: http://s3hh.wordpress.com/2011/03/28/lxc-clone/

**Comment by Donderda** [comment]
Hm. Any updates on this? Or a workaround? I need this... 👍

**Comment by ccope** [comment]
vagrant has built-in support for linked clones now, but it would require a bit of work to implement in this plugin. PR's are welcome.
