### ISSUE TITLE
vagrant-lxc-wrapper doesn't allow 'which' on Fedora

### ISSUE THREAD

**Issue by detached** [fgrehm/vagrant-lxc#322]
On Fedora which is an alias, defined in `/etc/profile.d/which2.sh`:

```````
> which which 
which='alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde'
	/usr/bin/alias
	/usr/bin/which
```````

Vagrant-lxc does a `sudo_wrapper.run("which", "lxc-create")`  that validates the command and the allowed arguments. As the arguments from the alias are not whitelisted by vagrant-lxc-wrapper, the program fails with the misleading error:

```````
The `lxc` package does not seem to be installed or is not accessible on the PATH.
```````

In the debug log you can see:
```````
 INFO subprocess: Starting process: ["/usr/bin/sudo", "/usr/local/bin/vagrant-lxc-wrapper", "which", "lxc-create"]
DEBUG subprocess: stderr: Invalid arguments for command /bin/which, provided args: ["lxc-create"]
```````

**Comment by thePanz** [comment]
@fgrehm I am facing this same error in ArchLinux after a recent upgrade.

The issue is the following:  `which lxc-ls` returns `/bin/lxc-ls`, that's fine, but the problem is that the whole `/bin` is a symlink to `/usr/bin`. I guess leading to the same error as above.
