### ISSUE TITLE
Ephemeral containers support

### ISSUE THREAD

**Issue by fgrehm** [fgrehm/vagrant-lxc#33]
Reference: https://help.ubuntu.com/12.04/serverguide/lxc.html#lxc-ephemeral

**Comment by nvtkaszpir** [comment]
Wondering if this would be still valid?

**Comment by globin** [comment]
Where would you have a usecase here?

**Comment by nvtkaszpir** [comment]
Of course with ephemeral lxc you cannot for example do 'reboot' because container disappears, so this would be really an edge case for those who seek speeding up 'vagrant destroy -f' and 'vagrant up' on tmpfs - especially if you have a lot of ram but your normal storage is slow or almost full.
