### ISSUE TITLE
vagrant ssh returns "The container hasn't been created yet."

### ISSUE THREAD

**Issue by ataraxis** [fgrehm/vagrant-lxc#334]
It's happened a couple times now that I'll have a working environment, then suddenly I can no longer ssh into it with the error "The container hasn't been created yet" (even while simultaneously being ssh'd into it from another terminal window). `lxc-ls --active` shows the container running:

```
project_default_1418633719208_25806
```

Trying to do `vagrant up` results in errors because the redir rules are still in place and cause a conflict. `vagrant destroy` has no effect, I have to manually kill the redir processes and destroy the container.

Debug log for `vargrant ssh` here: https://gist.github.com/ataraxis/b64a3d5cf6082a111c21

**Comment by rtkrruvinskiy** [comment]
FWIW, I've also come across this, although very infrequently. Vagrant appears to just "lose track" of the underlying LXC container. I haven't been able to make out what's going on, though. Did you by any chance notice a pattern to these occurrences? For some reason I half suspect that maybe this can happen when running two vagrant commands in separate shells at the same time, but I have no proof for this.
