### ISSUE TITLE
Default the `lxc__bridge_name` to 'vlxcbr1'?

### ISSUE THREAD

**Issue by tknerr** [fgrehm/vagrant-lxc#341]
The README says 

> On its current state, there is a requirement for setting the bridge name that will be created and will allow your machine to comunicate with the container

Which is true, you have to specify `lxc__bridge_name: 'vlxcbr1'` if you want private networking with the lxc provider to work. It sounds like this would be improved in a future release. 

For a short term / quick win improvement, would it make sense to simply default the `lxc__bridge_name` to 'vlxcbr1'?

That way you don't have to modify each `private_network` configuration across Vagrantfiles.

**Comment by tknerr** [comment]
P.S.: it seems that you can safely add `lxc__bridge_name` to existing `private_network` configurations without affecting other providers. At least for virtualbox it was not a problem.

See here:
https://github.com/tknerr/sample-infrastructure-repo/commit/fbcf0bfd4539c3d72edee8e4f9e424d5bc15a13a#diff-23b6f443c01ea2efcb4f36eedfea9089R25

**Comment by fgrehm** [comment]
Eventually we might see some "automagical bridge creation" in place, making the `lxc__bridge_name` completely optional, but it's not on my short term plans. If someone is up for putting a PR with that I'll consider bringing it in for next release on 1.x series :-)
