### ISSUE TITLE
Check vagrant version

### ISSUE THREAD

**Issue by elektito** [fgrehm/vagrant-lxc#343]
When I run `vagrant init fgrehm/precise64-lxc` I get this:

```
Failed to load the "vagrant-lxc" plugin. View logs for more details.
```

Vagrant proceeds to create a Vagrantfile though so then I run `vagrant up --provider=lxc` and this is what I get:

```
/home/mostafa/.vagrant.d/gems/gems/vagrant-lxc-1.1.0/lib/vagrant-lxc/provider.rb:30:in `sudo_wrapper': undefined method `sudo_wrapper_path' for Vagrant::LXC:Module (NoMethodError)
        from /home/mostafa/.vagrant.d/gems/gems/vagrant-lxc-1.1.0/lib/vagrant-lxc/provider.rb:39:in `ensure_lxc_installed!'
        from /home/mostafa/.vagrant.d/gems/gems/vagrant-lxc-1.1.0/lib/vagrant-lxc/provider.rb:24:in `initialize'
        from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:116:in `new'
        from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:116:in `initialize'
        from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:434:in `new'
        from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:434:in `machine'
        from /usr/lib/ruby/vendor_ruby/vagrant/plugin/v2/command.rb:142:in `block in with_target_vms'
        from /usr/lib/ruby/vendor_ruby/vagrant/plugin/v2/command.rb:175:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/plugin/v2/command.rb:175:in `block in with_target_vms'
        from /usr/lib/ruby/vendor_ruby/vagrant/plugin/v2/command.rb:174:in `map'
        from /usr/lib/ruby/vendor_ruby/vagrant/plugin/v2/command.rb:174:in `with_target_vms'
        from /usr/share/vagrant/plugins/commands/up/command.rb:56:in `block in execute'
        from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:210:in `block (2 levels) in batch'
        from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:208:in `tap'
        from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:208:in `block in batch'
        from <internal:prelude>:10:in `synchronize'
        from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:207:in `batch'
        from /usr/share/vagrant/plugins/commands/up/command.rb:55:in `execute'
        from /usr/lib/ruby/vendor_ruby/vagrant/cli.rb:38:in `execute'
        from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:484:in `cli'
        from /usr/bin/vagrant:127:in `<main>'
```

I'm using Vagrant 1.4.3 on Ubuntu 14.04 and I installed vagrant-lxc as mentioned in the README by running `vagrant plugin install vagrant-lxc`.

[This](https://gist.github.com/elektito/5b3edacffd576a0185eb) is the result of the `up` command when run with `VAGRANT_LOG=debug`. [This](https://gist.github.com/elektito/235c27cded3991621e1e) is the results for the aforementioned `init` command.

**Comment by blindmatrix** [comment]
Haven't verified it yet as I also get this error with same config as you, but docs state that you need Vagrant 1.5+ so I guess that's the issue =/

**Comment by tzach** [comment]
@blindmatrix thanks for the advice!
Had the same problem as @elektito , I was indeed running an old Vagrant release.

**Comment by blindmatrix** [comment]
I upgraded to Vagrants latest DEB (1.7.2) and it indeed solved this. There should be a version check in Vagrant when it downloads plugins to make sure they will still work.

**Comment by fgrehm** [comment]
Sorry for the silence and thanks for confirming that upgrading to a recent vagrant works. I'll try adding a vagrant version check to the plugin for the next release so other don't have to figure this out on their own.

**Comment by elektito** [comment]
This indeed seems to be the problem. I didn't realize the vagrant version distributed in Ubuntu 14.04 repos is so old. Thanks.

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
