### ISSUE TITLE
Hostname does not set after init private networking 

### ISSUE THREAD

**Issue by artemkaint** [fgrehm/vagrant-lxc#345]
Hostname does not set after init private networking  and vagrant up has freezed

<pre>
<code>
==> abcp: Setting hostname...
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Re-using SSH connection.
 INFO ssh: SSH is ready!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  (sudo=false)
DEBUG ssh: Exit status: 0
DEBUG guest: Searching for cap: change_host_name
DEBUG guest: Checking in: ubuntu
DEBUG guest: Found cap: change_host_name in ubuntu
 INFO guest: Execute capability: change_host_name [#<Vagrant::Machine: abcp (Vagrant::LXC::Provider)>, "abcp"] (ubuntu)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: hostname -f (sudo=true)
DEBUG ssh: stdout: vagrant-base-precise-amd64

DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: echo 'abcp' > /etc/hostname (sudo=true)
DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: grep 'vagrant-base-precise-amd64' /etc/hosts (sudo=false)
DEBUG ssh: stdout: 127.0.1.1   vagrant-base-precise-amd64

DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: sed -ri 's@^(([0-9]{1,3}\.){3}[0-9]{1,3})\s+vagrant\-base\-precise\-amd64(\s.*)?$@\1 abcp abcp@g' /etc/hosts (sudo=true)
DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: [ `lsb_release -c -s` = hardy ] (sudo=false)
DEBUG ssh: Exit status: 1
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: service hostname start (sudo=true)
DEBUG ssh: stdout: hostname stop/waiting

DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: hostname --fqdn > /etc/mailname (sudo=true)
DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: ifdown -a; ifup -a; ifup -a --allow=hotplug (sudo=true)
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...

</code></pre>

**Comment by artemkaint** [comment]
upd:  this error has repeated when i set private ip in network 10.0.3.*

**Comment by fgrehm** [comment]
Are you on an Ubuntu host? If yes the private network config is likely to be colliding with the `lxcbr0` that is already in place. If not, please LMK what is your host distro and version and the Vagrantfile you are using.

**Comment by globin** [comment]
If the bridge removal was the issue this is fixed in master.
