### ISSUE TITLE
Containers loose port

### ISSUE THREAD

**Issue by tiagobrito** [fgrehm/vagrant-lxc#346]
I'm having some weird behavior with port assignment with vagrant-lxc.
Some containers start without a port assigned, and after a day or two some containers loose their used ports.

```
ps aux | grep cport=22
root      5645  0.0  0.0   4444   652 ?        S    11:24   0:00 sh -c redir --lport=2202 --caddr=10.0.4.209 --cport=22 2>/dev/null
root      5646  0.0  0.0   6440   684 ?        S    11:24   0:00 redir --lport=2202 --caddr=10.0.4.209 --cport=22
root     24713  0.0  0.0   4444   216 ?        S    Feb20   0:00 sh -c redir --lport=2205 --caddr=10.0.4.150 --cport=22 2>/dev/null
root     24714  0.0  0.0   6440   244 ?        S    Feb20   0:00 redir --lport=2205 --caddr=10.0.4.150 --cport=22
```

```
sudo lxc-ls --fancy
NAME                                                    STATE    IPV4        IPV6  AUTOSTART  
--------------------------------------------------------------------------------------------
a_default_1424690597599_87619       RUNNING  10.0.4.209  -     NO
b_default_1424453591807_16598       RUNNING  10.0.4.151  -     NO
c_web_1424344214122_57329           STOPPED  -                  -     NO

```

As you can see the container a_default_1424690597599_87619 is running with IP 10.0.4.209, with port 22 assigned as it is suppose.
The problem is in the container b_default_1424453591807_16598 and c_web_1424344214122_57329.
The container  b_default_1424453591807_16598 is also running but the port was lost (it had one at Feb 20)
The container c_web_1424344214122_57329 is stopped but I have one port 22 associated to 10.0.4.150 that isn't assigned.

**Comment by fgrehm** [comment]
Sorry but this had never happened to me before. How does your Vagrantfile look like and what distro are you using as the host system?

**Comment by tiagobrito** [comment]
I'm closing this issue because I think the cause isn't related to vagrant / vagrant-lxc.
Just to context:
I'm using RabbitMQ to start php processes execute vagrant commands e.g. ```vagrant up```, ```vagrant halt```. All works as expected, but when the RabbitMQ worker/consumer is restarted or stopped the child process's ports are clean.
