### ISSUE TITLE
lxc_start.c: main: 291 Executing '/sbin/init' with no configuration file may crash the host

### ISSUE THREAD

**Issue by nexxTM** [fgrehm/vagrant-lxc#348]
I'm trying the quick start but I'm getting this error:

> ==> default: Waiting for machine to boot. This may take a few minutes...
> Timed out while waiting for the machine to boot. This means that
> Vagrant was unable to communicate with the guest machine within
> the configured ("config.vm.boot_timeout" value) time period.

When I do `lxc-start -n $(cat .vagrant/machines/default/lxc/id)` I'm getting this error:

> lxc-start: lxc_start.c: main: 291 Executing '/sbin/init' with no configuration file may crash the host

I'm using:
* Ubuntu 14.10
* lxc-1.1.0~alpha2
* vagrant 1.7.2
* vagrant-lxc 1.1.0

**Comment by fgrehm** [comment]
Have you tried [this](https://github.com/fgrehm/vagrant-lxc/issues/333#issue-52575565)?

**Comment by nexxTM** [comment]
That works. Thanks and sorry I didn't found that on my own.
