### ISSUE TITLE
sudoers documentaiton out of date

### ISSUE THREAD

**Issue by Ramblurr** [fgrehm/vagrant-lxc#349]
The [sudoers wiki doc](https://github.com/fgrehm/vagrant-lxc/wiki/Avoiding-'sudo'-passwords) is out of date.

I run vagrant on a user with no sudo general permissions, so I need to setup the sudoers exceptions in a different user. I hacked the script on the wiki to use the correct values $SUDO_USER and $HOME in my use case.

But in the latest version the vagrant-lxc is using different commands. Could you please update the wiki?

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
