### ISSUE TITLE
Overlayfs Vagrant

### ISSUE THREAD

**Issue by herisanu** [fgrehm/vagrant-lxc#351]
How do you actually use overlayfs with vagrant-lxc? I saw, the pull request, I saw the added code. Could you please add an example on how to use it?

I'm using it on Centos 7, i've added the kernel from kernel-ml and recompiled lxc-1.1.0 for it to work. Now I can't figure out how to make vagrant-lxc use it.

Regards,
Heri

**Comment by fgrehm** [comment]
I have never used it before, maybe @pruby can help us out on this one?

**Comment by tjheeta** [comment]
It appears that the only setting required is:
lxc.backingstore = "overlayfs"
