### ISSUE TITLE
Metadata removed and container not created with aborted operation

### ISSUE THREAD

**Issue by fritzvd** [fgrehm/vagrant-lxc#358]
On Ubuntu LTS 14.04.1 running vagrant lxc (vagrant 1.7.2 and vagrant-lxc 1.1.0) when I cancel an operation after giving the wrong sudo password (although it might even be without the first error). E.g.

```
vagrant ssh
[sudo password for] ....
[sudo password for]
`CTRL-C`
```

I lose my vagrant box. But not entirely it still exists as an lxc container. All the metadata is lost (in `.vagrant/machines/default/lxc`)

**Comment by fgrehm** [comment]
I'll try digging into this but in the meantime, would you be able to try enabling passwordless `sudo`? It should avoid those type of issues https://github.com/fgrehm/vagrant-lxc#avoiding-sudo-passwords

**Comment by fritzvd** [comment]
Thanks. That will at least prevent this from happening to easily. Thanks. 
It's mysterious isn't it?

**Comment by fgrehm** [comment]
Yeah, my initial thoughts would be some weirdness around dealing with machines in parallel, but later I noticed you are having trouble with `vagrant ssh` which is a single machine command only.

**Comment by fritzvd** [comment]
Yes. Well I don't have the problems anymore with the `vagrant lxc sudoers`
command.
And `vagrant ssh` was just an example. It happens on all kinds of commands,
when I decide not to open the box after being prompted for the password.

I'm not a rubyist (python/js) but I took a look in the repo and poked
around a bit.

Could it be that the validate! function here fails:
https://github.com/fgrehm/vagrant-lxc/blob/3b45b92d1a5533e7ce3e12da3cc6c476779582ec/lib/vagrant-lxc/provider.rb#L45-L61

When the function does not resolve, might it do funky things? I went over
it a few times and when I break (CTRL+D) the sudo password prompt it gives
back:

*==> default: The container hasn't been created yet.*

After that the metadata folder is empty



On 1 April 2015 at 20:42, Fabio Rehm <notifications@github.com> wrote:

> Yeah, my initial thoughts would be some weirdness around dealing with
> machines in parallel, but later I noticed you are having trouble with vagrant
> ssh which is a single machine command only.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fgrehm/vagrant-lxc/issues/358#issuecomment-88590609>.
>



-- 
*Nelen & Schuurmans *

 Postbus 1219  3500 BE Utrecht
Zakkendragershof 34-44 Utrecht
tel. 030 2330 200
@fritzvd <http://twitter.com/fritzvd>
www.nelen-schuurmans.nl

**Comment by leorochael** [comment]
@fgrehm, maybe this is related to #336? They both have the "*`^C` killed my vagrant metadata*" vibe...

**Comment by fgrehm** [comment]
I think @fritzvd  is right on spot, just dunno how to fix that yet :cry:

**Comment by darkhelmet** [comment]
This is pretty old, pinging for attention. I've hit this numerous times, as I'm quick to run a command and realize an error and quickly ctrl+c, only to find my VM no longer works and I have to rebuild.

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
