### ISSUE TITLE
vagrant halt tries to modify the container's filesystem

### ISSUE THREAD

**Issue by ccope** [fgrehm/vagrant-lxc#360]
This is fine for the default folder backingstore, but won't work with LVM/BTRFS/ZFS. Move this functionality to a command run in lxc-attach, or remove the code entirely.

**Comment by ccope** [comment]
Is running without the ability to attach still supported? If so, can we deprecate that? LXC 1.0 has been out for a while now, and users shouldn't have much trouble upgrading. Any command trying to mess with the rootfs of a container will fail with non-dir backingstores, so they should all be converted to attach commands.

**Comment by fgrehm** [comment]
> Is running without the ability to attach still supported? If so, can we deprecate that? LXC 1.0 has been out for a while now, and users shouldn't have much trouble upgrading.

I'm cool with that, we just need a user friendly message when someone tries to use the plugin on a pre 1.0 lxc :smile:

**Comment by ccope** [comment]
Ok, I'll see about adding a deprecation notice tonight.

**Comment by ccope** [comment]
not deprecating 1.0.0 for now, solved the issue without requiring attach.
