### ISSUE TITLE
Public Network

### ISSUE THREAD

**Issue by dragoscirjan** [fgrehm/vagrant-lxc#364]
Hello there,

I noticed the plugin does not support public network config option.

Please take a look at http://askubuntu.com/questions/256304/public-ip-address-for-lxc-container

I used concept on a server (before taking a look on vagrant - I'm developing a small server automation tool now based on vagrant) and it works like a charm.

Maybe you can implement a similar idea within your plugin as well.

Also, if you need help (even though I don't know ruby at all) please tell me. I'm more than eager to learn and help.

**Comment by ccope** [comment]
Can you describe exactly what you need? The plugin allows you to specify a bridge and use either a static IP that you provide or rely on DHCP.

**Comment by dragoscirjan** [comment]
It's about the basic vagrant configuration for public_network, let me
understand its dynamics on Virtualbox though. I may have rushed with this
request.

Right now I'm unable to understand how public_network and private_network
seem to work.

On Sat, Apr 11, 2015 at 2:23 AM, Cam Cope <notifications@github.com> wrote:

> Can you describe exactly what you need? The plugin allows you to specify a
> bridge and use either a static IP that you provide or rely on DHCP.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fgrehm/vagrant-lxc/issues/364#issuecomment-91715082>.
>



-- 
-----------------------------------------------------------------
Cristian - Dragos, Cirjan
-----------------------------------------------------------------
Email: dragos.cirjan@gmail.com
Email (work): dragosc@itmcd.ro
Skype: dragos.cirjan, YM: cirjandragos, MSN: cirjandragos
Telefon: +40 726/355762, +40 771/437090, +40 771/437095
