### ISSUE TITLE
multiple private networks issue

### ISSUE THREAD

**Issue by jeanfabrice** [fgrehm/vagrant-lxc#365]
Hi

Defining multiple 'private_network' entry in Vagrantfile, does not "work as expected" (i.e works as it does using the virtualbox provider)

Here is network part of my setup : 

```
(1..2).each do |i|
  config.vm.define "n#{i}" do |node|
    node.vm.network "private_network", :adapter=>2, ip: "192.168.1.#{i}",virtualbox__intnet: "cluster", lxc__bridge_name:'cluster'
    node.vm.network "private_network", :adapter=>3, ip: "192.168.0.#{i}",virtualbox__intnet: "private", lxc__bridge_name:'private'
end
```

Bringing up `n1` with lxc provider : 
- does not throw any error
- create both `eth1`and `cluster`bridge
- does not create `eth2`
- does not create `private` bridge

Next, bringing up `n2`with lxc provider : 
- throw an error and halt at the `pipework` stage while creating the second interface
- does not create `eth2`
- do create  `private` bridge

Despite the strange behaviour (where, using the same configuration,  the second container start throw an error while the first one not), do you confirm that multiple private network is not supported ?

My investigations so far : 
- pipework supports a `-i`option to specify the interface. When not used, it defaults to `eth1`
- On the other side, vagrant-lxc does not seem to take care of the ':adapter' parameter from the Vagrantfile. Neither it uses the `-i`option of `pipework`.

Thank you.

**Comment by fgrehm** [comment]
Oh yeah, I missed out the support for the `adapter` parameter [over here](https://github.com/fgrehm/vagrant-lxc/blob/0365ad4a17563e1384fd81f9267b9f4186b05f17/lib/vagrant-lxc/action/private_networks.rb#L24-L36) :panda_face:

**Comment by jeanfabrice** [comment]
Hi, 
here are the [Vagrant logs](https://gist.github.com/jeanfabrice/4faf47fc67fc59529a62) and the [Vagrantfile](https://gist.github.com/jeanfabrice/d6a45f8f3418712bd252)

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
