### ISSUE TITLE
rpc.mountd fails for NFS share using BTRFS

### ISSUE THREAD

**Issue by adri** [fgrehm/vagrant-lxc#366]
First of all thank you for your awesome work! I really appreciate using vagrant-lxc. 

This issue is actually a question. I wonder if BTRFS supports NFS, I couldn't find any useful information about it and wondered if you had a tipp. 
1. I've setup a Ubuntu 14.04 VM (`parallels/ubuntu-14.04`), installed LXC and formatted the `/` system with **BTRFS**. 
2. In this VM I'm running a VM based on `fgrehm/trusty64-lxc`.

Everything seems to boot up well except when I enable the NFS shared folder. I followed the [FAQ](https://github.com/fgrehm/vagrant-lxc/wiki/FAQ#does-nfs-synced-folders-work) and according to [this](http://technuts.tru.my/2013/08/28/how-to-mount-nfs-in-lxc-container/) I've changed `/etc/apparmor.d/lxc/lxc-default` to:

```
profile lxc-container-default flags=(attach_disconnected,mediate_deleted) {
  #include <abstractions/lxc/container-base>

  # the container may never be allowed to mount devpts.  If it does, it
  # will remount the host's devpts.  We could allow it to do it with
  # the newinstance option (but, right now, we don't).
#  deny mount fstype=devpts,

  mount fstype=nfs,
  mount fstype=nfs4,
  mount fstype=rpc_pipefs,
}
```

When booting up the VM I receive this message

```
exportfs: /vagrant/vms/vagrant-providers-symfony does not support NFS export
==> default: Mounting NFS shared folders...
SNIP!
mount -o 'vers=3,udp' 10.0.3.1:'/vagrant/vms/vagrant-providers-symfony' /mnt/vagrant-QX58m0GAW2Wn
SNIP!
mount.nfs: access denied by server while mounting 10.0.3.1:/vagrant/vms/vagrant-providers-symfony
```

On the "host" `/var/log/syslog` shows the following entries.

```
Apr 19 16:59:51 vagrant rpc.mountd[1241]: authenticated mount request from 10.0.3.185:952 for /vagrant/vms/vagrant-providers-symfony (/vagrant/vms/vagrant-providers-symfony)
Apr 19 16:59:51 vagrant rpc.mountd[1241]: qword_eol: fflush failed: errno 22 (Invalid argument)
Apr 19 16:59:51 vagrant rpc.mountd[1241]: Cannot export /vagrant/vms/vagrant-providers-symfony, possibly unsupported filesystem or fsid= required
```

Do you have an idea how I could get the shared folder to work properly? Preferably with using NFS.
Thanks again!

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
