### ISSUE TITLE
"vagrant lxc sudoers" ask for sudo

### ISSUE THREAD

**Issue by hashar** [fgrehm/vagrant-lxc#369]
When running `vagrant lxc sudoers` to generate a sudo list, it ironically ask me for sudo:

```
vagrant lxc sudoers
[sudo] password for hashar: 
```

Would be nice to spurts the sudoers config file to stdout so one can review it and manually add it.

**Comment by fgrehm** [comment]
yeah, that is a good idea :) but I'll close it as a duplicate of https://github.com/fgrehm/vagrant-lxc/issues/350, please subscribe to that issue for updates on it!
