### ISSUE TITLE
feat req: support lxd

### ISSUE THREAD

**Issue by battlemidget** [fgrehm/vagrant-lxc#373]
Would be cool to have support for lxd: https://linuxcontainers.org/lxd/, though im not sure this warrants a new vagrant plugin. Let me know if this is something that should be separate from the lxc plugin

**Comment by ccope** [comment]
This plugin interacts with the lxc tools directly, I doubt it would be easy to adapt to LXD. LXD is also geared more towards managing containers across multiple hosts. What features from LXD do you want to see here?

**Comment by battlemidget** [comment]
There are several speed improvements gained from using its image based workflow. Also lxd complements the existing lxc tools.

**Comment by ccope** [comment]
I think we could take advantage of the images by just using the lxc-download template. Anything else specific?

**Comment by fgrehm** [comment]
Yeah, I agree with @ccope. Not to say that I have not had the time to keep up with this project recently and I'd prefer not to introduce new functionality without having me or someone else to support it.

If someone is capable of adapting this plugin to work with LXD and is up for sending a PR I'd me more than happy to review and give write access to the repo in case the person is up to hang around to support potential issues that might arise. On the other hand, if someone is up for kicking off a separate plugin to get LXD support in vagrant I'd be up for helping out getting things started.

@battlemidget sorry but I personally don't have any short term plans to implement this so I'll close this issue (but please feel free to comment in case you have anything to add! I'll still get notified on it)

**Comment by niccolox** [comment]
@battlemidget @fgrehm I would like to see a LXD Vagrant solution

**Comment by niccolox** [comment]
can we open this issue so that its easier to find? 

https://roots.io/linux-containers-lxd-as-an-alternative-to-virtualbox-for-wordpress-development/

https://www.reddit.com/r/Ubuntu/comments/48a2i4/lxd_with_vagrant/

**Comment by nmabhinandan** [comment]
Another thing to notice is that the lxd runs in unprivileged mode.

**Comment by PierrePaul** [comment]
lxd can also pack and share containers as image... :)
