### ISSUE TITLE
Ability to disable prefixing all commands with sudo

### ISSUE THREAD

**Issue by rrader** [fgrehm/vagrant-lxc#374]
I'm using ArchLinux with https://aur.archlinux.org/pkgbase/linux-user-ns-enabled/ kernel, which has user namespaces.
So, it would be cool if I can provide some option to vagrant-lxc to avoid running all commands via sudo.

**Comment by ccope** [comment]
This duplicates #312 (which I haven't had time to work on yet). If you think you could help with anything on the list in that issue, pull requests are welcome!

**Comment by rrader** [comment]
Ok, got it. I'm not Ruby expert, but I will try ;)

**Comment by fgrehm** [comment]
Yup, @ccope is right. @rrader please subscribe to that issue for updates!
