### ISSUE TITLE
Call for Maintainers

### ISSUE THREAD

**Issue by fgrehm** [fgrehm/vagrant-lxc#375]
Hey guys!

Life, as it tends to do, has progressed for me in such a way that I am no longer able to devote time to maintaining this plugin, especially as I no longer use it on a daily basis.

As such, this project has been neglected and I apologize for that. I am hoping there is someone who would be willing to step up and take over maintaining this project so it gets the attention it deserves. If you would like to do so, please respond with a comment explaining a bit about what you would like to do as a maintainer of this project. I'll then add one or more of those users as collaborators along with @ccope which is already a collaborator here on GitHub.

Thanks everyone!

**Comment by fpletz** [comment]
Hi @fgrehm! As mentioned on #376, we would be very happy to help develop and maintain vagrant-lxc! As we're using it for our projects and even some of the developers at our customers, we would also be able to dedicate some company time @mayflower for this.

It would be cool if you could give @globin and myself write access for now. We both will probably be the main contributors from @mayflower in the next few weeks.

Thanks a lot for your work on vagrant-lxc, much appreciated! And again, if you happen to find yourself in Munich, please drop by and let us invite you to some beers or whatever you prefer! :beers: :clap:

**Comment by fgrehm** [comment]
There you go! Enjoy your superpowers :muscle: 

Thanks **A LOT** guys for stepping up for this! You have no idea how happy I am that this plugin is not going to become abandonware :smile:

As I mentioned on the other issue, when you feel that it is the time to cut a release, please get everything ready in a PR and `@ping` me on it so I can have a quick look and add you 2 as a collaborator on RubyGems.org

/cc @ccope since you also got write access here

**Comment by stucki** [comment]
Thanks a lot for taking over the maintenance! Thanks a ton also to Fabio who did an awesome job until here!

Now looking forward to many new improvements... :-)

**Comment by dragoscirjan** [comment]
Hi guys. I'm not a ruby person, but I'd start learning if necessary. I'm highly dependent on this plugin, so if you need help, please say so.

**Comment by ccope** [comment]
@fpletz do you have any plans on when the next release will happen? It looks like we have a couple of fixes lined up that are basically ready to go.

**Comment by fpletz** [comment]
@ccope Sorry, I was on vacation the last few weeks. We should definitely make a release soon. My plan would be next week. I will look at the issues and PRs in the next few days.

**Comment by ccope** [comment]
Cool, sounds good!

**Comment by slattery** [comment]
Thanks @fpletz.

**Comment by fgrehm** [comment]
@ccope @fpletz @globin I see that you guys are ready to cut a release, do you mind opening up a PR with the changes for that (like bumping the version and updating the changelog) so that I can have my :eyes: on it before giving you access to the gem on RubyGems? :beers:

**Comment by globin** [comment]
If no-one beats me to, will do tomorrow.

**Comment by fgrehm** [comment]
Given that 1.2.0 has been released with as close to zero intervention as it could get from me, I'm going to consider this solved :)

Thanks a lot for keeping the fire burning!

**Comment by hsoft** [comment]
It's my turn to pass on the "fire". I haven't been using vagrant to manage LXC containers for many months now and I don't expect I'll be doing it again in the foreseeable future. This project will need a new maintainer.

**Comment by hsoft** [comment]
I don't use Windows, so that's one less problem to have.

As for projects I work on nowadays, they're simple enough that a container isn't needed. A good old Makefile is enough. I still do webdev, so I need mysql/postgres around, but I manage them outside the projects I work on. Projects just need to be configurable enough to allow any kind of setup: the developer is then smart enough to setup their env as they please.

I still use LXC for testing environments for Gentoo packaging, but not through vagrant. I use it directly, with [brmgr](https://github.com/CameronNemo/brmgr) to handle networking.

**Comment by rvanlaar** [comment]
Hi @hsoft,

I would like to get this package in a better state.

Today I was hit by: https://github.com/fgrehm/vagrant-lxc/issues/475
The latest master doesn't seem to have this issue.

First of, how can a release be made of current master?
What's the work necessary for this? 

- Roland

**Comment by fgrehm** [comment]
Moved to https://github.com/fgrehm/vagrant-lxc/issues/499
