### ISSUE TITLE
error on lxc-create

### ISSUE THREAD

**Issue by crashbtz** [fgrehm/vagrant-lxc#384]
Hi,

I'm trying to run a lxc in a vm with vagrant and I'm stuck in the lxc creation step.
Here what I did.
I have a lxc which was made by someone else before I arrive.
1) I made a box file like yours (fgrehm/trusty64-lxc)
    in it, you can find a metadata.json

    {
        "provider": "lxc",
        "version":  "1.0.0",
        "built-on": "Sat Sep 21 21:10:00 UTC 2013"
    }

and a rootfs.tar.gz which contains a rootfs folder with all the lxc in it

2) Then I have a first Vagrantfile which build the VM

    # -*- mode: ruby -*-
    # vi: set ft=ruby :

    # Vagrantfile API/syntax version.
    VAGRANTFILE_API_VERSION = "2"

    # Vargrant file for LXC constainer for ETS
    # Don't touch unless you know what you're doing!

    Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
          config.vm.box = "ubuntu/trusty64"
          config.vm.hostname = "lxc-dev"

          config.vm.synced_folder "deployment/", "/deployment"
          config.vm.boot_timeout = 600
          config.vm.network "private_network", ip: "192.168.42.100", auto_config: false
          config.vm.network "public_network"

          config.vm.provider "virtualbox" do |vb|
              vb.customize ["modifyvm", :id, "--memory", "512"]
              vb.customize ["modifyvm", :id, "--cpus", "1"]
              vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
              vb.gui = true
          end

          config.vm.provision :shell, inline: "sudo apt-get update"
          config.vm.provision :shell, inline: "sudo apt-get install -y lxc lxc-templates cgroup-lite redir bridge-utils python-pip"

          config.vm.provision :shell, :inline => BOX_SETUP_SCRIPT, privileged: false
          config.vm.provision :shell, :inline => VAGRANT_STARTUP_SCRIPT, run: "always", privileged: false
    end

    ## -- SETUP script - ONE TIME ONLY !
    BOX_SETUP_SCRIPT = <<END
    #!/bin/bash

    cat << EOF > /tmp/lxcbr1.cfg
    auto eth1
    iface eth1 inet manual
        up ifconfig eth1 promisc up
        down ifconfig eth1 promisc down

    auto lxcbr1
    iface lxcbr1 inet static
        address 192.168.42.100
        broadcast 192.168.42.255
        netmask 255.255.255.0
        bridge_ports eth1
        bridge_stp off
        bridge_waitport 0
        bridge_fd 0
    EOF

    sudo mv /tmp/lxcbr1.cfg /etc/network/interfaces.d/lxcbr1.cfg

    sudo service networking restart
    sudo ifup lxcbr1

    echo '*************************'
    echo '***  VAGRANT install  ***'
    cd /tmp
    wget -q https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.5_x86_64.deb

    sudo dpkg -i vagrant_1.6.5_x86_64.deb
    vagrant plugin install vagrant-lxc
    END

    ## -- Startup script
    VAGRANT_STARTUP_SCRIPT = <<END
        #!/bin/bash

        echo '*************************'
        echo '*** LXC VM deployment ***'
        cd /deployment
        vagrant up
    END

3) And finally the Vagrantfile which build the lxc in the VM which has been built in the step 2

    VAGRANTFILE_API_VERSION = "2"

    Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.define :lxc1 do |box|
        box.vm.hostname = "ets-vm-21"
        box.vm.box = "ets-vm-21"
        box.vm.box_url = "file:///deployment/resources/vagrant-lxc-21/vagrant-lxc-21.box"
        box.vm.provider :lxc do |provider|
            provider.customize "network.type", "veth"
                provider.customize "network.flags", "up"
                provider.customize "network.link", "lxcbr1"
                provider.customize "network.ipv4", "192.168.42.10/24"
            end
        end
    end

Here is the error:

    ==> default: There was an error executing ["sudo", "lxc-create", "-B", "best", "--template", "vagrant-tmp-deployment_lxc1_1441808747234_97103", "--name", "deployment_lxc1_1441808747234_97103", "--", "--tarball", "/home/vagrant/.vagrant.d/boxes/ets-vm-21/0/lxc/rootfs.tar.gz"]
    ==> default: 
    ==> default: For more information on the failure, enable detailed logging by setting
    ==> default: the environment variable VAGRANT_LOG to DEBUG.
    The SSH command responded with a non-zero exit status. Vagrant
    assumes that this means the command failed. The output for this command
    should be in the log above. Please read the output to determine what
    went wrong.

And when I try manually:

    sudo lxc-create -B best --template vagrant-tmp-deployment_lxc1_1441815361362_9510 --name deployment_lxc1_1441815361362_9510 -- --tarball /home/vagrant/.vagrant.d/boxes/ets-vm-21/0/lxc/rootfs.tar.gz
    lxc_container: lxccontainer.c: get_template_path: 867 No such file or directory - bad template: vagrant-tmp-deployment_lxc1_1441815361362_9510
    lxc_container: lxccontainer.c: lxcapi_create: 1264 bad template: vagrant-tmp-deployment_lxc1_1441815361362_9510
    lxc_container: lxc_create.c: main: 271 Error creating container deployment_lxc1_1441815361362_9510

I have the impression it's a matter of rights, like the template can't be created or something but I don't how to resolve this.

Thanks for your help

**Comment by globin** [comment]
Can you try vagrant-lxc master? The template handling has been simplified since the last release.

**Comment by bpiselli** [comment]
Hi @globin 
I am working with @crashbtz on this And we don't get your answer ?
The issue is we are building the vm.box from an existing debian LXC following
http://fabiorehm.com/blog/2013/07/18/crafting-your-own-vagrant-lxc-base-box/

But it does not seem to work. Even while following the guide line per line we have a vagratn failure on 
```
There was an error executing ["sudo", "lxc-create", "-B", "best", "--template", "vagrant-tmp-test-import-2_default_1441887178122_57852", "--name", "test-import-2_default_1441887178122_57852", "--", "--tarball", "/home/vagrant/.vagrant.d/boxes/my-box-2/0/lxc/rootfs.tar.gz"]

For more information on the failure, enable detailed logging by setting
the environment variable VAGRANT_LOG to DEBUG.
```

**Comment by globin** [comment]
```
vagrant plugin install vagrant-lxc
```
You are installing the currently released version. On the master branch there is a commit (611a86ce84c59efcd602ed38230b27b41d4dd9f6) that could fix this. You could have a try if that fixes this but I'll try to make sure a new release gets on its way the next few days.

**Comment by fgrehm** [comment]
FTR - there are some notes on how to build the plugin from sources here: https://github.com/fgrehm/vagrant-lxc/wiki/Development#installing-the-plugin-from-source

**Comment by globin** [comment]
Ah since you're here @fgrehm, would you mind releasing 1.2.0? I believe we're good to go.

/cc @fpletz @ccope

**Comment by bpiselli** [comment]
Hey thanks @globin and @fgrehm for the very fast answers !

We are struggling to install master directly from source : mainly because of some folder access that force us to do ```gem install bundler``` as sudo user failing the next step :(
Issue might come from the fact that we are doing this in a encapsuled VM

Yes it would be incredible to create a release 1.2.0 and deploy it :)

**Comment by agriffis** [comment]
@globin Since 1.2.0 and now 1.2.1 are released, I think this can be closed

**Comment by globin** [comment]
Yep, thanks!
