### ISSUE TITLE
Timed out while waiting for the machine to boot

### ISSUE THREAD

**Issue by gotlium** [fgrehm/vagrant-lxc#388]
```
root@gotlium-kvm# vagrant plugin install vagrant-lxc
Installing the 'vagrant-lxc' plugin. This can take a few minutes...
Installed the plugin 'vagrant-lxc (1.1.0)'!

root@gotlium-kvm# vagrant up --provider=lxc
Bringing machine 'default' up with 'lxc' provider...
==> default: Box 'fgrehm/trusty64-lxc' could not be found. Attempting to find and install...
    default: Box Provider: lxc
    default: Box Version: >= 0
==> default: Loading metadata for box 'fgrehm/trusty64-lxc'
    default: URL: https://atlas.hashicorp.com/fgrehm/trusty64-lxc
==> default: Adding box 'fgrehm/trusty64-lxc' (v1.2.0) for provider: lxc
    default: Downloading: https://atlas.hashicorp.com/fgrehm/boxes/trusty64-lxc/versions/1.2.0/providers/lxc.box
==> default: Successfully added box 'fgrehm/trusty64-lxc' (v1.2.0) for 'lxc'!
==> default: Importing base box 'fgrehm/trusty64-lxc'...
==> default: Setting up mount entries for shared folders...
    default: /vagrant => /usr/src/vm
==> default: Starting container...
==> default: Waiting for machine to boot. This may take a few minutes...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

Tested on new Ubuntu-Server 14.04 under KVM.

```
# lxc-ls -f
NAME          STATE    IPV4  IPV6  AUTOSTART  
--------------------------------------------
lp-translate  STOPPED  -     -     NO   
```

It happened when I use pre-defined variables for memory. Example:

```
APP_MEMORY = "#{ENV['VM_MEMORY'] || '2048'}"
config.vm.provider :lxc do |lxc, override|
    lxc.customize 'cgroup.memory.limit_in_bytes', APP_MEMORY
end
```

**Comment by ccope** [comment]
You'll need to run `sudo lxc-start -n lp-translate --log-level=debug --logpriority=debug --logfile start.log` and then post the contents of start.log (you have to log to the file, --log-level won't change the output to the console). Your container could have failed to start for many reasons depending on the contents of your Vagrantfile/container config.

**Comment by gotlium** [comment]
Problems when I using pre-defined vars. You can see example on my comment.

    APP_MEMORY = "#{ENV['VM_MEMORY'] || '2048'}"
    config.vm.provider :lxc do |lxc, override|
        lxc.customize 'cgroup.memory.limit_in_bytes', APP_MEMORY
    end

**Comment by gotlium** [comment]
Enabled debug

    export VAGRANT_LOG=DEBUG

That output: https://gist.github.com/gotlium/9e1babce8b09afd9c420

**Comment by globin** [comment]
Please do as recommended by @ccope to get the lxc error message

**Comment by ccope** [comment]
2048 will limit the container to 2KB, which is too small to start properly. Add a suffix, like '2048M' or '2G'.

**Comment by gotlium** [comment]
I think it's a bug, because on another providers it's working properly.

**Comment by fgrehm** [comment]
Well, that config section block is provider specific and each provider will have its own way of doing things. Users should not expect them to have the same behavior (even though vbox and parallels might work the same way)

_If_ we had a top level memory config, like:

```ruby
Vagrant.configure("2") do |config|
  config.vm.memory = '2048'

  # instead of
  # config.vm.provider :lxc do |lxc, override|
  #    lxc.customize 'cgroup.memory.limit_in_bytes', APP_MEMORY
  # end
end
```

Then yes, I'd consider it a bug

HTH :beers:

**Comment by gotlium** [comment]
I use 4 providers on Vagrantfile. For Windows - VirtualBox, OS X - Parallels, Linux - LXC/KVM. 
And I mean why you are using bytes? Why you can not use by default megabytes and standard directives? I'm understand when I want to customize cgroups, but by default you can use simple variable `lxc.vm.memory`. That easy and standard behavior for many providers.

    Explicit is better than implicit.
                     The Zen of Python

**Comment by ccope** [comment]
`APP_MEMORY + 'M'` would also work.

**Comment by gotlium** [comment]
I'm not understand why you won't add standard directives for CPU and MEM?

**Comment by globin** [comment]
We'd appreciate a PR implementing this in a compatible way to other providers. :beers:

**Comment by ccope** [comment]
For CPU in particular, it is hard to make it similar to other providers because container scheduling works differently from VM's. You can either pin to particular cores, or set a relative priority. You can't create 3 machines each with 1 cpu core without explicitly assigning a specific core per container.

**Comment by gotlium** [comment]
I'm understand it. You can write about this option in wiki:)

**Comment by kadiiskiFFW** [comment]
I had the same problem (Ubuntu 14.04, using Cibox). The problem was that the nfs server wasn't started. Try with `sudo service nfs-kernel-server start` and than `vagrant up` - this worked with me.

**Comment by ameyaagashe** [comment]
Any idea when this is going to be fixed??

**Comment by richard-scott** [comment]
I get this far every now and then:

```
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.
```
However, after this errors the "config.vm.provision" sections in my Vagrantfile fire up and run just fine. I used Ansible to provision the server, and that can SSH in just fine.

**Comment by ccope** [comment]
@richard-scott I don't think your comments are related to the original issue here, Virtualbox and LXC are unrelated.

Closing this issue because I don't think there's anything actionable left here.
