### ISSUE TITLE
Bridge in private network is destroyed prematurely

### ISSUE THREAD

**Issue by winks** [fgrehm/vagrant-lxc#395]
Hi,
I tried to convert our current VBox Vagrantfile to LXC and it mostly works, so thanks for the awesome work!

One little thing that I either didn't grasp or works unintuitively or it's a bug :)

2 machines, they have these config lines for private ips:

```
    config.vm.network :private_network, ip: "172.20.10.3", lxc__bridge_name: 'vlxcbr1'

    config.vm.network :private_network, ip: "172.20.10.14", lxc__bridge_name: 'vlxcbr1'
```

Everything is fine:

```
$ vagrant status
[..]
files                     running (lxc)
puppet                    running (lxc)

vagrant@files:~$ ping puppet
64 bytes from puppet (172.20.10.3): icmp_req=1 ttl=64 time=0.060 ms

$ sudo brctl show
bridge name     bridge id               STP enabled     interfaces
lxcbr0          8000.fee91a6a38cd       no              vethB2VLJG
                                                        vethIQBQPL
vlxcbr1         8000.0e65032a3fca       no              veth1pl12289
                                                        veth1pl9279
```

Now if I halt and restart one of them:

```
$ vagrant halt files
==> files: Attempting graceful shutdown of VM...
==> files: Removing bridge 'vlxcbr1'...
$ vagrant up files
$ vagrant ssh files
[..]
vagrant@files:~$ ping puppet
From 172.20.10.14 icmp_seq=1 Destination Host Unreachable
```

My first (and only idea) was to use `vlxbr2` for `files`, but then it doesn't seem to start from the get-go.

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
