### ISSUE TITLE
Consider to cache lxc calls, the cli is slow

### ISSUE THREAD

**Issue by malinoff** [fgrehm/vagrant-lxc#397]
Hello, I have 20 lxc-based VMs defined in my Vagrantfile:

``` bash
$ time vagrant status
[snip]
vagrant status  7,92s user 2,09s system 98% cpu 10,113 total
$ time vagrant ssh-config
[snip]
vagrant ssh-config  10,03s user 2,41s system 99% cpu 12,515 total
```

The reason of this slowness is that `Vagrant::LXC::Driver::Cli` executes a lot of unnecessary commands:

``` bash
$ VAGRANT_LOG=debug vagrant status 2>status_log
$ grep lxc-ls status_log | wc -l
20

$ VAGRANT_LOG=debug vagrant ssh-config 2>ssh_config_log
$ grep lxc-ls ssh_config_log | wc -l
20
$ grep 'lxc-attach", "-h' ssh_config_log | wc -l
20
$ grep lxc-attach ssh_config_log | wc -l 
120
```

I'm asking to cache these invocations between instances of `Vagrant::LXC::Driver::Cli`, I've made some caching on `Provider` level (cached MachineState instance in `@machine_state`) and already gained a significant speedup:

``` bash
$ time vagrant status
[snip]
vagrant status  5,19s user 1,03s system 99% cpu 6,224 total
$ time vagrant ssh-config
[snip]
vagrant ssh-config  8,39s user 1,73s system 99% cpu 10,134 total
```

**Comment by hsoft** [comment]
@malinoff I recently change `lxc-attach` calls for `lxc-info` ones. The change will be there in the upcoming v1.3. I didn't benchmark it the way you did, but I'm thinking that maybe this speeds things up a bit?

**Comment by malinoff** [comment]
I'm afraid I won't have ability to check :) I stopped using vagrant long time ago

**Comment by hsoft** [comment]
I hope you don't mind if I close the issue then.
