### ISSUE TITLE
ipdb rendering issue

### ISSUE THREAD

**Issue by ajeebkp23** [fgrehm/vagrant-lxc#403]
Hi, 

I just started using vagrant-lxc recently. Everything works almost as usual.

ipdb is a enhanced version of python debugger(pdb). In python script we put it between lines like `import ipdb; ipdb.set_trace()`, just like pdb.

When i use `python manage.py runserver 0.0.0.0:8000` (django runserver), after `vagrant ssh` into container.

When it reaches debugging point it renders wrongly.

ie. `Quotation.sobjects.exclude(pk__in=approved_quotes)`. When i paste code before, to debugger, then press `<Home>` key or `<Ctrl>+<a>`. then the cursor is placed at `Quotation.s`cursor_here`objects.exclude(pk__in=approved_quotes)`. 
and if i type `something` then it is rendered as `Quotation.ssomethingQuotation.sQuotation.sobjects.exclude(pk__in=approved_quotes)`.

I am using `redir` for port forwarding.
Also my Host os is
>Ubuntu 14.04 Gnome
>3.13.0-76-generic x86_64

And i am using guest image 
https://atlas.hashicorp.com/fgrehm/boxes/trusty64-lxc

Any suggestions to fix this?

If this issue is not related vagrant-lxc, please tell me (if you can) to go where.

**Comment by ccope** [comment]
This sounds unrelated to vagrant-lxc, and possibly vagrant entirely. It may be an issue with the way you are pasting code. See http://stackoverflow.com/questions/33934325/how-to-paste-multiple-lines-to-an-ipdb-shell-in-python
