### ISSUE TITLE
Box files and delta distributions

### ISSUE THREAD

**Issue by gwillem** [fgrehm/vagrant-lxc#412]
We use vagrant-lxc as an integral part of our workflow. But I've been eying Docker for their nice aufs/layered distribution model. Especially since our build pipeline produces new LXC boxes and those take a while to download (~500MB).

Ideally, I would love the flexibility of LXC (resembling a full VM) with the distribution features of Docker. How do you handle this? I could replace `vagrant box update` with a custom rsync but that looks flakey.

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
