### ISSUE TITLE
Error on creating new VMs: cgfsng_create: No such file or directory

### ISSUE THREAD

**Issue by RussianCow** [fgrehm/vagrant-lxc#414]
Whenever I create a new VM via `vagrant up`, I get the same error as noted [here](https://github.com/lxc/lxc/issues/999). Lots of things changed with my setup recently (I upgraded to Ubuntu 16.04, updated LXC to 2.0.1, and am using the Linux 4.6 kernel), though I don't know which triggered this bug (though I'm guessing it was the Linux kernel upgrade, as 4.6 introduced cgroup namespaces).

I don't know enough about how containers or cgroups work on a low level to understand what the actual problem is, but adding the below line to `scripts/lxc-template` solves the problem for me:

```
echo "lxc.aa_allow_incomplete = 1" >> ${LXC_PATH}/config
```

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
