### ISSUE TITLE
lxc-attach error

### ISSUE THREAD

**Issue by bakicdj** [fgrehm/vagrant-lxc#427]
I keep getting this error when i try to use glenux/jessie64-lxc box. But for ubuntu it works just fine. Does anyone have similar issue?

`INFO interface: Machine: error-exit ["Vagrant::LXC::Errors::ExecuteError", "There was an error executing lxc-attach\n\nFor more information on the failure, enable detailed logging by setting\nthe environment variable VAGRANT_LOG to DEBUG."]`

**Comment by hsoft** [comment]
Does the issue persist with v1.3.1? We use `lxc-info` to fetch IP at boot now.

**Comment by hsoft** [comment]
In fact, this is a duplicate to #308
