### ISSUE TITLE
Add -s flag to lxc-destroy

### ISSUE THREAD

**Issue by sephii** [fgrehm/vagrant-lxc#429]
`vagrant destroy` will fail if your box has any associated snapshots:

> Destroying drifter-jessie64-base_default_1481013000756_8417 failed: drifter-jessie64-base_default_1481013000756_8417 has snapshots.

I know Vagrant doesn't allow to create snapshots so you're not supposed to have any, but you can still create snapshots manually and in that case I'd expect `vagrant destroy` to still work properly. Adding the `-s` flag to `lxc-destroy` would fix this.

**Comment by strarsis** [comment]
Doesn't vagrant offer snapshots, at least for native providers like virtualbox? https://www.vagrantup.com/docs/cli/snapshot.html

**Comment by sephii** [comment]
You're right, I didn't know about this. It looks like vagrant-lxc doesn't support this though, but I guess it would be quite simple to add since it's just about forwarding the commands to `lxc-snapshot`.

**Comment by fgrehm** [comment]
This is something I wanted to do for a long time, but unfortunately I no longer use this plugin. I think @ccope started some work around that not long ago, not sure what's the latest info on that.

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
