### ISSUE TITLE
Invalid arguments for command /usr/bin/lxc-create

### ISSUE THREAD

**Issue by hackel** [fgrehm/vagrant-lxc#430]
Just playing with this for the first time.  It appears the lxc-wrapper script is failing when calling lxc-create.  I've included the debug output.
`DEBUG subprocess: stderr: Invalid arguments for command /usr/bin/lxc-create, provided args: ["-B", "best", "--template", "/home/hackel/.vagrant.d/gems/gems/vagrant-lxc-1.2.1/scripts/lxc-template", "--name", "lxc-test_default_1481915208483_8705", "--", "--tarball", "/home/hackel/.vagrant.d/boxes/fgrehm-VAGRANTSLASH-precise64-lxc/1.2.0/lxc/rootfs.tar.gz", "--config", "/home/hackel/.vagrant.d/boxes/fgrehm-VAGRANTSLASH-precise64-lxc/1.2.0/lxc/lxc-config"]`

I tried this using the default configuration in an auto-generated Vagrantfile.  I tried both the fgrehm/precise64-lxc and developerinlondon/ubuntu_lxc_xenial_x64 boxes, but I don't think that's the issue here.

Ubuntu 16.10
lxd: 2.6.2-0ubuntu3~ubuntu16.10.1~ppa1
lxc1: 2.0.6-0ubuntu4~ubuntu16.10.1~ppa1
vagrant: 1.8.5+dfsg-2

[vagrant-debug-log.txt](https://github.com/fgrehm/vagrant-lxc/files/658025/vagrant-debug-log.txt)

**Comment by brejoc** [comment]
With version 2 this command is no longer existing. A lot of things have changed and e.g. `lxc launch ubuntu:14.04 my-ubuntu` can instead be used to launch a container. Also LXD now has a REST-API which might be a better fit: https://linuxcontainers.org/lxd/rest-api/

There is even a Ruby-Client: http://jeffshantz.github.io/hyperkit/

**Comment by iamjvn** [comment]
I may have encountered a similar issue. The following worked for me, but it's unclear why:
```
$ vagrant plugin list
$ vagrant plugin uninstall vagrant-lxc
$ sudo mv /usr/local/bin/vagrant-lxc-wrapper /tmp
$ vagrant plugin install vagrant-lxc
$ export VAGRANT_LOG=debug
$ vagrant up <your node name>
```

**Comment by aidalgol** [comment]
I get almost the exact same error on Debian jessie (stable), which ships lxc 1.0.6, which still has the command `lxc-create`.

System info:
Debian 8.7
lxc 1:1.0.6-6+deb8u5
vagrant 1.6.5+dfsg1-2

[vagrant-debug-log.txt](https://github.com/fgrehm/vagrant-lxc/files/933151/vagrant-debug-log.txt)
