### ISSUE TITLE
Bundler reporting error while installing vagrant-lxc

### ISSUE THREAD

**Issue by kebab-mai-haddi** [fgrehm/vagrant-lxc#434]
This is the error that is shown by Vagrant:

> An error occurred while installing vagrant-share (1.1.6), and Bundler cannot continue.
Make sure that `gem install vagrant-share -v '1.1.6'` succeeds before bundling
![image](https://cloud.githubusercontent.com/assets/13495855/22251844/3ba6f7c0-e272-11e6-8870-5bae9462630e.png)

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
