### ISSUE TITLE
Hang during vagrant halt/reload with Xenial guest on Yakkety host and Vagrant 1.9.1

### ISSUE THREAD

**Issue by rvanlaar** [fgrehm/vagrant-lxc#437]
Since upgrading vagrant to 1.9.1 I can't shutdown ubuntu 16.04 guests. 
How can we fix this?

It hangs during the shutdown. 
This also happens when I execute shutdown -h now from the terminal inside the guest.

VAGRANT 1.9.1
Host ubuntu 16.10 (Yakkety)
Guest: 16.04 (Xenial)

The xenial container worked before the vagrant upgrade. 
A Trusty container works.

The relevant part from the debug log:

```
DEBUG guest: Found cap: halt in linux
 INFO guest: Execute capability: halt [#<Vagrant::Machine: default (Vagrant::LXC::Provider)>] (ubuntu)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: shutdown -h now (sudo=true)
DEBUG ssh: stderr: mesg: ttyname failed:
DEBUG ssh: stderr: Inappropriate ioctl for device

DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
```
The Log for Ubuntu Trusty (14.04):
```
DEBUG guest: Found cap: halt in linux
 INFO guest: Execute capability: halt [#<Vagrant::Machine: default (Vagrant::LXC::Provider)>] (ubuntu)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: shutdown -h now (sudo=true)
DEBUG ssh: stderr: stdin: is not a tty

DEBUG ssh: Exit status: 0
```

**Comment by ccope** [comment]
Ah, I think I encountered this with xenial containers myself. Make sure your container image has libpam-systemd installed, otherwise networking stops before sshd and the connection gets left open.

**Comment by rvanlaar** [comment]
Thanks @ccope installing `libpam-systemd` and rebooting the container fixed it.
