### ISSUE TITLE
NFS requires host-only network

### ISSUE THREAD

**Issue by lassizci** [fgrehm/vagrant-lxc#440]
I have this network configuration in my vagrantfile:

```
config.vm.network "private_network", ip: "192.168.1.3", lxc__bridge_name: "virbr0"
```

and when trying to use nfs synced folders, I get:

>NFS requires a host-only network to be created.
>Please add a host-only network to the machine (with either DHCP or a
>static IP) for NFS to work.

How do I need to configure to get NFS working? Or could it be some kind of incompatibility?

```
$ vagrant --version
Vagrant 1.9.2

$ vagrant plugin list
vagrant-lxc (1.2.3)
vagrant-share (1.1.7, system)

$ lxc-start --version
2.0.7
```

The setup works with VirtualBox when I have the same network config, but without `lxc__bridge_name`

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
