### ISSUE TITLE
Arch linux and networking

### ISSUE THREAD

**Issue by thePanz** [fgrehm/vagrant-lxc#441]
After reading lot of posts on how to configure Arch Linux with Vagrant-LXC, I finally got it working and booting my VM correctly with SystemD.
The network configuration looks even easier than the one provided in the wiki! :)
Here my steps:

0. Install the required libs `sudo pacman -Syu dnsmasq net-tools bridge-utils` (dnsmasq is required by lxc-net.service, while the other 2 seems to be related)
1. Ensure `lxc-net` is started by LXC `sudo echo "USE_LXC_BRIDGE=true" >> /etc/default/lxc-net` (see: https://bbs.archlinux.org/viewtopic.php?id=223807)
2. Start the `lxc-net` service: `sudo systemctl start lxc-net`
   - check the logs from: `sudo systemctl status lxc-net` to make sure no errors are reported
   - check that `lxcbr0` is shown by `ip a`

Could we update the Wiki accordingly?

ps: if port-forwarding is used, the "redir" package from AUR is required too (`yaourt redir`)

**Comment by rvlander** [comment]
This won't work for me. No interface shows up in the container and vagrant script then crashes.

**Comment by thePanz** [comment]
Which is the output of `sudo systemctl status lxc-net`?

**Comment by kovacskri** [comment]
This worked for me, thanks for the advice.

**Comment by ccope** [comment]
Updated the wiki page. Thanks @thePanz !

**Comment by thePanz** [comment]
Thank you @ccope ! :)
