### ISSUE TITLE
multiple private networks not working

### ISSUE THREAD

**Issue by brianbourke75** [fgrehm/vagrant-lxc#442]
I am attempting to use the experimental private network settings with two machines like ..

ts1config.vm.network "private_network", ip: "192.168.50.4", lxc__bridge_name: 'virbr0'

and 

ts2config.vm.network "private_network", ip: "192.168.50.5", lxc__bridge_name: 'virbr0'

I can get one connection working but not both, any suggestions? (vagrant-lxc version 1.2.1)

**Comment by nicobrevin** [comment]
When you say not working, what do you mean?  You can't ssh?  They can't communicate between themselves on those IPs?  `vagrant up` fails?

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
