### ISSUE TITLE
pipework: "Could not find a process inside container"

### ISSUE THREAD

**Issue by cpfeiffer** [fgrehm/vagrant-lxc#463]
Pipework fails with the above error message. Upstream already has a fix for 3 years, maybe you coud incorporate that?
https://github.com/jpetazzo/pipework/commit/e0560cca51cec43225d3c9b724a2b5da836145fa

Thanks!

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
