### ISSUE TITLE
Redir 3 forwarded ports are not being cleared correctly

### ISSUE THREAD

**Issue by ethervoid** [fgrehm/vagrant-lxc#467]
Hi,

We've been experiencing problems with redir, version 3.1, not being cleared after a `vagrant reload`

I checked the code and found that is being done [here](https://github.com/fgrehm/vagrant-lxc/blob/master/lib/vagrant-lxc/action/clear_forwarded_ports.rb#L17).

The problem is that is getting the wrong PIDs from [here](https://github.com/fgrehm/vagrant-lxc/blob/master/lib/vagrant-lxc/action/clear_forwarded_ports.rb#L37)

For example, my redir PID for port 3000 is `10459` but in the file redir_3000 is stored the PID `10456`

I'm going to paste some outputs here:

 ```
ethervo+ 10459  0.0  0.0   6656   108 ?        Ss   16:46   0:00 redir 127.0.0.1 3000 10.0.3.131 3000
 ```

and the file cat

```
cat /media/data/development/vm/cartodb_lxc_xenial/.vagrant/machines/default/lxc/pids/redir_3000.pid                                                                                                                       [16:47:18]
10456
```

It seems like [this part](https://github.com/fgrehm/vagrant-lxc/blob/484b8681000690e97607bbe7d536f4ccb49ea9be/lib/vagrant-lxc/action/forward_ports.rb#L52) is not returning a correct PID for that process

Looks like [spawn](https://github.com/fgrehm/vagrant-lxc/blob/484b8681000690e97607bbe7d536f4ccb49ea9be/lib/vagrant-lxc/action/forward_ports.rb#L97) could be returning the parent pid instead of the final one?

**Comment by ethervoid** [comment]
More info:

If you go to `irb` and do:

```
irb(main):002:0> spawn 'redir 127.0.0.1:3000 10.0.3.131:3000 2>/dev/null'
=> 29411
```

but if you make a `pgrep` you get
```
❯ pgrep redir                                                                                           [17:37:35]
29413
```

**Comment by hsoft** [comment]
Thanks for the detailed report. It turns out that "foreground mode" was the key. I've noticed that it was a new option compared to v2.x, so that was a hint... and it was it.

I've pushed a fix on `master`. Could you try and confirm the fix?

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
