### ISSUE TITLE
vagrant-lxc-wrapper fails when TMPDIR is not /tmp

### ISSUE THREAD

**Issue by eigengrau** [fgrehm/vagrant-lxc#472]
`vagrant-lxc-wrapper` currently expects that `TMPDIR=/tmp`. E.g., `TMPDIR=/run/user/1000 vagrant up` will fail, with no specific error message, since whitelist regexps only refer to `/tmp`, whereas any temporary files created will reside elsewhere.

**Comment by hsoft** [comment]
I'm not sure of the security implications of adding that kind of flexibility to a whitelist-based sudoers file. This whitelist already seems a bit fragile security-wise, it seems to me like it should be avoided in favor of unprivileged containers.

De-hardcoding `/tmp` looks like something that will have many side-effects and that will require bug squashing in many places (or widening the whitelist so much that it becomes even more insecure).

If you produce a patch, we can continue the conversation around a specific proposition.

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
