### ISSUE TITLE
Disable /vagrant mount in the guest

### ISSUE THREAD

**Issue by Aguay-val** [fgrehm/vagrant-lxc#476]
Hi there,

I'm using vagrant-lxc since a while but now i'm facing a problem.
I'd like to disable the mount of the "/path/to/project" into "guest:/vagrant".

By default, all the time you launch a new vagrant lxc container, vagrant lxc create a mount entry as follow :
`lxc.mount.entry=/home/aguay/Workspace/test vagrant none bind,create=dir 0 0`

Even if i don't specify any "mount entry" in my Vagrantfile this folder is _always_ added to my lxc config file.

Is there anyway to disable it ? it could lead to a security issue. Is a pretty bad idea, in my opinion, to be able to change the Vagrantfile into the guest.

Thanks

**Comment by ccope** [comment]
This is default vagrant behavior. You can disable it with `config.vm.synced_folder '.', '/vagrant', disabled: true`

**Comment by Aguay-val** [comment]
Oh thank you ! 

I thought it was a vagrant-lxc behavior.
