### ISSUE TITLE
Using packer to create base boxes?

### ISSUE THREAD

**Issue by ladar** [fgrehm/vagrant-lxc#478]
It appears that `packer` supports exporting Vagrant boxes for LXC, but it isn't clear what the inputs are, and how they're used? Can I build a box using QEMU, and then export it using the `vagrant` post-processor, with `lxc` as the type? That is how I handle generating `docker` boxes. Is there a guide somewhere? 

For reference, this page lists LXC as a valid `vagrant` type for the post processor:

https://www.packer.io/docs/post-processors/vagrant.html

And these rather old, non conclusive issues discuss support:

https://github.com/fgrehm/vagrant-lxc/issues/219
https://github.com/hashicorp/packer/issues/790

But I couldn't find anything recent, or definitive. Nor could I find a guide on how to use to generate base boxes.

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
