### ISSUE TITLE
Privilege escalation in lxc-wrapper

### ISSUE THREAD

**Issue by Aguay-val** [fgrehm/vagrant-lxc#482]
Hello,

I use vagrant-lxc for a while and we found a privilege escalation in the lxc-wrapper which may cause a risk for the host system.

If you want to restrict access to root user for a user by using "sudo /path/to/lxc-wrapper" there is a privilege escalation which result in a root shell.

Before releasing the privilege escalation i would like to help fix the issue.

Does someone can help me ? PM me.

**Comment by Aguay-val** [comment]
Ok i think i have found a way to prevent a privilege escalation.

I have to do more tries to be sure it's safe.

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
