### ISSUE TITLE
Provision fails when ipcalc is installed - eval ipcalc fails

### ISSUE THREAD

**Issue by onknows** [fgrehm/vagrant-lxc#491]
On Ubuntu 18.04 I noticed that setting up a private network will fail when `ipcalc` is installed.  After `apt remove ipcalc` it is working again.

In the `pipework` script line 392
```
      if installed ipcalc; then
        eval $(ipcalc -b $IPADDR)
```
Is there supposed to be a eval here? This doesn't make any sense. Why would we want to execute the output of ipcalc? This looks like malicious code. 

```
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["/usr/bin/sudo", "/usr/bin/env", "/home/user/.vagrant.d/gems/2.4.9/gems/vagrant-lxc-1.4.3/scripts/pipework", "lxcbr3", "bkd-base-lxc", "1.1.4.100/24"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: /home/user/.vagrant.d/gems/2.4.9/gems/vagrant-lxc-1.4.3/scripts/pipework: 1: eval: Address:: not found
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999
DEBUG subprocess: Exit status: 127
ERROR warden: Error occurred: There was an error executing ["sudo", "/usr/bin/env", "/home/user/.vagrant.d/gems/2.4.9/gems/vagrant-lxc-1.4.3/scripts/pipework", "lxcbr3", "bkd-base-lxc", "1.1.4.100/24"]

For more information on the failure, enable detailed logging by setting
```

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
