### ISSUE TITLE
Support for LXC client on MacOS

### ISSUE THREAD

**Issue by Credentive-Sec** [fgrehm/vagrant-lxc#495]
I have the LXC client installed on Mac, and it is happily interfacing with an LXD instance running on a Linux-based Server in my basement. I can run all of the lxc commands locally and they are executed on the server. I would like to use vagrant-lxc on top of vagrant running on my mac, but when I try to execute the vagrant command, I get the following error:

```
 credentive@Roberts-MBP# vagrant
Vagrant failed to initialize at a very early stage:

The LXC provider only works on Linux. Please try to use
another provider.
```

It appears that there is a check somewhere in the code that just bails if it detects a Mac instance. Are there other problems with LXC on Mac, or is this just an oversight?

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
