### ISSUE TITLE
 Error while vagrant up vagrant "There was an error executing lxc-info"

### ISSUE THREAD

**Issue by VasylPetrashkevych** [fgrehm/vagrant-lxc#497]
Getting the following error -
` INFO interface: Machine: error-exit ["Vagrant::LXC::Errors::ExecuteError", "There was an error executing lxc-info\n\nFor more information on the failure, enable detailed logging by setting\nthe environment variable VAGRANT_LOG to DEBUG."]`

Using:
Manjaro: 21.1.0
Vagrant 2.2.16
LXC version 4.0.10

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
