### ISSUE TITLE
Vagrant 1.2.0 can't add box

### ISSUE THREAD

**Issue by nlamirault** [fgrehm/vagrant-lxc#79]
Hi, i would like to try vagrant-lxc :

$ vagrant box add quantal64 http://dl.dropbox.com/u/13510779/lxc-quantal-amd64-2013-05-08.box
Downloading or copying the box...
Extracting box...e: 0/s, Estimated time remaining: --:--:--)
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

bsdtar: Missing type keyword in mtree specification
x <html>
bsdtar: Missing type keyword in mtree specification
x <head><title>Found</title></head>
bsdtar: Missing type keyword in mtree specification
x <body>
bsdtar: Missing type keyword in mtree specification
x <h1>Found</h1>
bsdtar: Malformed attribute "resource" (114)
x <p>The
bsdtar: Malformed attribute "should" (115)
x you
bsdtar: Malformed attribute "--></p>" (45)
x <!--
bsdtar: Malformed attribute "noshade>" (110)
x <hr
bsdtar: Unrecognized key align="right">WSGI
x <div
bsdtar: Missing type keyword in mtree specification
x </body>
bsdtar: Missing type keyword in mtree specification
x </html>
bsdtar: Error exit delayed from previous errors.

Any idea ?

**Comment by g2graman** [comment]
@fgrehm Issue persists in vagrant version > 1.21:

    $ vagrant -v
    Vagrant 1.4.3

    $ vagrant box add laravel/homestead https://atlas.hashicorp.com/laravel/boxes/homestead
    Downloading box from URL: https://atlas.hashicorp.com/laravel/boxes/homestead
    Extracting box...e: 0/s, Estimated time remaining: --:--:--)
    The box failed to unpackage properly. Please verify that the box
    file you're trying to add is not corrupted and try again. The
    output from attempting to unpackage (if any):

    bsdtar: Error opening archive: Unrecognized archive format
